### ISSUE TITLE
More options for exporting and importing messages

### ISSUE THREAD

**Issue by Ezelty** [SilenceIM/Silence#195]
It would be great if we could pick a file to import messages (instead of just importing encrypted/plaintext backup without being able to chose the right backup). You could also add an option to name the backup file when we export the messages. If the user makes a backup when there's already a backup file in the default backup folder, the two backups have the same name so the older one is deleted. To avoid this, you could let the user chose the file's name and the folder, and/or add the time and date in the backup file's name, by default, instead of naming every backup "SMSSecurePlaintextBackup.xml", so that every backup have a different name.

In addition, there could be an option to import only some messages, for example only the messages after a certain date (like in SMS Backup & Restore), or only the messages from a contact.

Thank you!

**Comment by pR0Ps** [comment]
This is probably too much complexity to expose in the UI.

**Comment by BastienLQ** [comment]
Unstead of asking the user, why not adding a timestamp in filenames? Like `SMSSecurePlaintextBackup_2015-07-22_13-03.xml`.

**Comment by johanw666** [comment]
Then what to do with restoring the backups? Show a list of options to the user when there is more than 1 backup? Or just restore the most recent one and delegate the maintenance to the user with a file manager?

**Comment by Ezelty** [comment]
BastienLQ: that's exactly what I meant.
Johanw666: I think restoring the most recent backup would be the easiest option.

**Comment by axtux** [comment]
In most applications, file selection is done through default file manager so it shouldn't be that hard to add. You can also select an extension (here it would be .xml).

**Comment by pR0Ps** [comment]
Closing in favor of #412
