### ISSUE TITLE
SMSSecure doesn't receive SMS messages that are longer than a few lines...

### ISSUE THREAD

**Issue by StrikeOne** [SilenceIM/Silence#288]
I'm running CM11 ROM, almost bare bones system, no Gapps, no Google Play (no Google anything) and the only apps I have installed are Ghostery browser, Disconnect Search and SMSSecure.

I am not receiving some SMS's - I posted in the thread #157 the log file shortly after missing one and further info I've posted can be read there...

**Comment by StrikeOne** [comment]
The sender said it was approx. 30lines of text, 7 words per line. That's a big SMS, but it should still work... It does with any other messaging platform!

**Comment by StrikeOne** [comment]
Just had someone send me two MMS that have not arrived also

**Comment by Buom01** [comment]
Probably because big SMS are converted into MMS
Same probleme for some of my friends
