### ISSUE TITLE
Beta releases

### ISSUE THREAD

**Issue by pR0Ps** [SilenceIM/Silence#298]
We need to do beta releases. We can't have an update go out to everyone that causes crashes like this latest one.

Recommend enabling the beta channel on Google Play (and F-Droid too if beta release functionality exists on it) and allowing people to opt in to beta releases. Then once the build has soaked in beta for a while without causing issues (or has had the issues fixed) we can push it to everyone.

**Comment by benjiprod** [comment]
How can I do on F-Droid ?
I checked beta-release on F-Droid.

**Comment by johanw666** [comment]
I agree. I found issue 294 just by coincidence, and since I used several versions of master between 0.12.3 and 0.13.0 I'm not exactly sure about the state of my database (perhaps that has to do with the reported crashes?)

**Comment by tuxayo** [comment]
> How can I do on F-Droid ?

See the F-Droid app:
https://gitlab.com/fdroid/fdroiddata/blob/master/metadata/org.fdroid.fdroid.txt#L534
They have 0.97 as current version even if newer were released. So the default version the users install is 0.97(on the app, it will have a star next to it). But users can choose to test the non stable versions.

**Comment by tuxayo** [comment]
> We can't have an update go out to everyone that causes crashes like this latest one.

By the way what are the issue(s) that you are referring to?

**Comment by BastienLQ** [comment]
Next release (v0.14) will include dual-SIM and encrypted backup support. I will enable the beta channel starting from this.

**Comment by BLeQuerrec** [comment]
There is now a branch `unstable`. We will publish PRs into that and keep `master` for hot fixes or tested upstream changes.

**Comment by tuxayo** [comment]
So we have a beta branch that one should compile to test the beta if I understand correctly ?

If yes then it seems that this issue was about binary releases that more people could easily try compared to a source code branch.

**Comment by BLeQuerrec** [comment]
@tuxayo `unstable` will be the beta branch for upcoming F-Droid and Play Store beta releases. `master` is still for stable releases.

**Comment by tuxayo** [comment]
Good, so F-Droid beta releases are still planned, thanks for the clarification, I got confused by the issue being closed.
