### ISSUE TITLE
display issue with the Pebble

### ISSUE THREAD

**Issue by DonaldMorden** [SilenceIM/Silence#339]
Hi, I don't know if there is a way to fix that bug, when i receive an unencrypted sms, I can read it normally on my pebble. But when I receive an encrypted SMS, it displays coded on my pebble.
I hope that you'll manage to correct this problem, thank you!

**Comment by johanw666** [comment]
Perhaps the keys are out of sync. To solve that: when you are in the conversation, try clicking on the padlock icon and then "end secure session", after that, re-open it.

**Comment by denharad** [comment]
I'm having this problem with no passphrase on the application but an encrypted conversation. I figured this was intentional behaviour but I would like to request the ability to push unencrypted updates to a local device like the pebble.

**Comment by BastienLQ** [comment]
Closing as Pebble is discontinued.
