### ISSUE TITLE
Project load error on current master

### ISSUE THREAD

**Issue by johanw666** [SilenceIM/Silence#381]
I am trying to build the current master (03c3e9b) with Android Studio 2.0. Loading the project results in the file `SMSSecure\libs\com.amulyakhare.textdrawable\build.gradle` with the error: `Error:(8, 0) Cannot change dependencies of configuration ':libs:com.amulyakhare.textdrawable:classpath' after it has been resolved`. In settings, I see for gradle Version: 143.SNAPSHOT.

Any idea what I am missing? Should I upgrade or downgrade something? Apparently I have to upgrade my Gradle setup, will check this tomorrow.

Edit: After reading several topics on Stackoverflow I failed to fix the build. Can anyone build the current master in Android Studio?

**Comment by johanw666** [comment]
I solved it by deleting the section
```
    dependencies {
        classpath 'com.android.tools.build:gradle:2.0.0'
    }
```
from `SMSSecure\libs\org.whispersystems.libpastelog\build.gradle`.

From what I understand (but please correct me, I'm certainly no gradle expert) this variable was already somewhere defined (probably the main build script) and redefining it was not allowed.

**Comment by BastienLQ** [comment]
I can't reproduce this, even after removing `./build/`, `./.gradle/` and `~/.gradle/`.

**Comment by johanw666** [comment]
When building the latest master I had the same issue also with build,gradle from com.amulyakhare.textdrawable. A well, I can fix the build now but I don't like it that I don't understand what the exact problem is.

**Comment by BastienLQ** [comment]
Did you try to remove `./build/`, `./.gradle/` and `~/.gradle/`? Do you build SMSSecure with `./gradlew build`?

Which Java version do you have? Mine is:
```
$ java -version
java version "1.7.0_99"
OpenJDK Runtime Environment (IcedTea 2.6.5) (Gentoo icedtea-7.2.6.5-r1)
OpenJDK 64-Bit Server VM (build 24.95-b01, mixed mode)
```

**Comment by johanw666** [comment]
No, as I wrote I build it with Android Studio from the GUI, on Windows 7 64 bit. It uses JDK 1.8.0_74.

**Comment by BastienLQ** [comment]
Can you find which command Android Studio tries to run?

**Comment by johanw666** [comment]
It doesn't show in the settings and a quick Google search turned up empty. I could try emptying the gradle cache and see what that does.

**Comment by johanw666** [comment]
When loading the project, Android Studio asks if I want to update the Gradle plugin since the one the project uses is outdated. When I say "No" it builds fine.
