### ISSUE TITLE
[Feature Request] Private Key export/import (and also pubkeys DB)

### ISSUE THREAD

**Issue by ArchangeGabriel** [SilenceIM/Silence#382]
Hi,

As I’m going to switch OS soon, I’m going to need to reinstall everything. Is there any easy way of exporting/importing the private key to avoid issuing a new one and therefore needing all of my contacts to verify the new one?

Similarly, is there an easy way to import/export “public keys” DB to avoid rechecking all of my contacts keys?

I would love easy import/export features for this, but for my planned migration I could live with copying the app folder over if this works.

Thanks!

**Comment by pR0Ps** [comment]
A total backup option (keys, sessions, contact keys, etc) should be
available in the next release. In the meantime using something like
Titanium Backup, Helium, or oandbackup to back up the app and all it's data
should work.

**Comment by zoff99** [comment]
can you please make it possible to ONLY export all the keys (without messages) [my keys and friend keys]

**Comment by ArchangeGabriel** [comment]
Nice to hear. :) I agree that a checkboxing of desired item types backup would be the best. ;)

**Comment by BastienLQ** [comment]
@zoff99 We won't implement keys only backups because it is easy to clean up your database after an import.
