### ISSUE TITLE
Emoji does not match system

### ISSUE THREAD

**Issue by keeferrourke** [SilenceIM/Silence#384]
The emoji bundled with SMSSecure is an old version of the Google [NotoEmoji](https://github.com/googlei18n/noto-emoji). The project has been updated several times since the revision that appears to be bundled with SMSSecure, and as a result some emoji do not display properly in SMSSecure when inputting them, and they appear differently in sent messages than on the keyboard.

On systems which do not use the Google Emoji (e.g. Emoji One, etc.) this mismatch is slightly annoying. I would suggest that:
1. The bundled emoji be updated to the latest version as in the Noto Project
2. There be an option in settings to completely disable emoji replacement in the app &ndash; that is to allow the user to make use of the emoji already present in their system.

**Comment by oxodao** [comment]
2. That's what I recommanded in another Github Issue, that would be quite nice

**Comment by Siphonay** [comment]
I'm bumping this issue, I'd like to see an option to use the system emojis too.
