### ISSUE TITLE
Bad encrypted message

### ISSUE THREAD

**Issue by takiainen** [SilenceIM/Silence#385]
Used to work fine, but now smssecure somehow breaks the encryption and says " bad encrypted message ". I have to restart the encrypted session, but the problem repeats after a while. Where's the problem? I'm running Darkobas ROM on Oneplus one. Never had this issue before on any other ROM.

**Comment by BastienLQ** [comment]
Can you post a debug log grabbed right after receiving a bad encrypted
message?

**Comment by takiainen** [comment]
Tried sending a sms for myself. Result: "bad encrypted message". Here's log

04-23 13:56:16.272 19279 19306 W SmsSendJob: Sending message: 3330
04-23 13:56:16.272 19279 19306 W SmsTransportDetails: Padding message body out to: 63
04-23 13:56:16.272 19279 19306 W CanonicalAddressDatabase: Hitting DB on query [ADDRESS]
04-23 13:56:16.289 19279 19306 W SmsTransportDetails: Encoded Message Length: 152
04-23 13:56:16.291 19279 19279 W CanonicalAddressDatabase: Hitting DB on query [ADDRESS]
04-23 13:56:16.312 19279 19279 W CanonicalAddressDatabase: Hitting DB on query [ADDRESS]
04-23 13:56:16.323 19279 19306 W org.smssecure.smssecure.sms.MultipartSmsTransportMessage: Complete fragment size: 158
04-23 13:56:16.325 19279 19306 W SmsTransport: Secure divide into message parts: 1
04-23 13:56:16.337 19279 19279 W CanonicalAddressDatabase: Hitting DB on query [ADDRESS]
04-23 13:56:16.354 19279 19591 W MmsSmsDatabase: Executing query: SELECT _id, unique_row_id, body, type, thread_id, address, address_device_id, subject, date_sent, date_received, m_type, msg_box, status, part_count, ct_l, tr_id, m_size, exp, st, date_delivery_received, mismatched_identities, network_failures, transport_type, attachment_id, unique_id, mid, data_size, _data, ct, cl, cd, name, pending_push FROM (SELECT DISTINCT date_sent AS date_sent, date AS date_received, _id, 'SMS::' || _id || '::' || date_sent AS unique_row_id, NULL AS attachment_id, body, read, thread_id, type, address, address_device_id, subject, NULL AS m_type, NULL AS msg_box, status, NULL AS part_count, NULL AS ct_l, NULL AS tr_id, NULL AS m_size, NULL AS exp, NULL AS st, date_delivery_received, mismatched_identities, NULL AS network_failures, 'sms' AS transport_type, NULL AS unique_id, NULL AS mid, NULL AS data_size, NULL AS _data, NULL AS ct, NULL AS cl, NULL AS cd, NULL AS name, NULL AS pending_push FROM sms WHERE (thread_id = 126) UNION ALL SELECT DISTINCT date AS date_sent, date_received AS date_received, mms._id AS _id, 'MMS::' || mms._id || '::' || date AS unique_row_id, part._id AS attachment_id, body, read, thread_id, NULL AS type, address, address_device_id, NULL AS subject, m_type, msg_box, NULL AS status, part_count, ct_l, tr_id, m_size, exp, st, date_delivery_received, mismatched_identities, network_failures, 'mms' AS transport_type, unique_id, NULL AS mid, data_size, NULL AS _data, ct, cl, cd, name, pending_push FROM mms LEFT OUTER JOIN part ON part._id =  (SELECT part._id FROM part WHERE part.mid = mms._id LIMIT 1) WHERE (thread_id = 126) ORDER BY date_received DESC LIMIT 500)
04-23 13:56:16.379 19279 19279 W CanonicalAddressDatabase: Hitting DB on query [ADDRESS]
04-23 13:56:16.398 19279 19279 W CanonicalAddressDatabase: Hitting DB on query [ADDRESS]
04-23 13:56:16.653 19279 19305 W SmsSentJob: Got SMS callback: org.smssecure.smssecure.SendReceiveService.SENT_SMS_ACTION , -1
04-23 13:56:16.657 19279 19305 W MessageDatabase: Updating ID: 3330 to base type: 23
04-23 13:56:16.671 19279 19305 W MmsSmsDatabase: Executing query: SELECT _id, unique_row_id, body, type, thread_id, address, address_device_id, subject, date_sent, date_received, m_type, msg_box, status, part_count, ct_l, tr_id, m_size, exp, st, date_delivery_received, mismatched_identities, network_failures, transport_type, attachment_id, unique_id, mid, data_size, _data, ct, cl, cd, name, pending_push FROM (SELECT DISTINCT date_sent AS date_sent, date AS date_received, _id, 'SMS::' || _id || '::' || date_sent AS unique_row_id, NULL AS attachment_id, body, read, thread_id, type, address, address_device_id, subject, NULL AS m_type, NULL AS msg_box, status, NULL AS part_count, NULL AS ct_l, NULL AS tr_id, NULL AS m_size, NULL AS exp, NULL AS st, date_delivery_received, mismatched_identities, NULL AS network_failures, 'sms' AS transport_type, NULL AS unique_id, NULL AS mid, NULL AS data_size, NULL AS _data, NULL AS ct, NULL AS cl, NULL AS cd, NULL AS name, NULL AS pending_push FROM sms WHERE (thread_id = 126) UNION ALL SELECT DISTINCT date AS date_sent, date_received AS date_received, mms._id AS _id, 'MMS::' || mms._id || '::' || date AS unique_row_id, part._id AS attachment_id, body, read, thread_id, NULL AS type, address, address_device_id, NULL AS subject, m_type, msg_box, NULL AS status, part_count, ct_l, tr_id, m_size, exp, st, date_delivery_received, mismatched_identities, network_failures, 'mms' AS transport_type, unique_id, NULL AS mid, data_size, NULL AS _data, ct, cl, cd, name, pending_push FROM mms LEFT OUTER JOIN part ON part._id =  (SELECT part._id FROM part WHERE part.mid = mms._id LIMIT 1) WHERE (thread_id = 126) ORDER BY date_received DESC LIMIT 1)
04-23 13:56:16.696 19279 19595 W MmsSmsDatabase: Executing query: SELECT _id, unique_row_id, body, type, thread_id, address, address_device_id, subject, date_sent, date_received, m_type, msg_box, status, part_count, ct_l, tr_id, m_size, exp, st, date_delivery_received, mismatched_identities, network_failures, transport_type, attachment_id, unique_id, mid, data_size, _data, ct, cl, cd, name, pending_push FROM (SELECT DISTINCT date_sent AS date_sent, date AS date_received, _id, 'SMS::' || _id || '::' || date_sent AS unique_row_id, NULL AS attachment_id, body, read, thread_id, type, address, address_device_id, subject, NULL AS m_type, NULL AS msg_box, status, NULL AS part_count, NULL AS ct_l, NULL AS tr_id, NULL AS m_size, NULL AS exp, NULL AS st, date_delivery_received, mismatched_identities, NULL AS network_failures, 'sms' AS transport_type, NULL AS unique_id, NULL AS mid, NULL AS data_size, NULL AS _data, NULL AS ct, NULL AS cl, NULL AS cd, NULL AS name, NULL AS pending_push FROM sms WHERE (thread_id = 126) UNION ALL SELECT DISTINCT date AS date_sent, date_received AS date_received, mms._id AS _id, 'MMS::' || mms._id || '::' || date AS unique_row_id, part._id AS attachment_id, body, read, thread_id, NULL AS type, address, address_device_id, NULL AS subject, m_type, msg_box, NULL AS status, part_count, ct_l, tr_id, m_size, exp, st, date_delivery_received, mismatched_identities, network_failures, 'mms' AS transport_type, unique_id, NULL AS mid, data_size, NULL AS _data, ct, cl, cd, name, pending_push FROM mms LEFT OUTER JOIN part ON part._id =  (SELECT part._id FROM part WHERE part.mid = mms._id LIMIT 1) WHERE (thread_id = 126) ORDER BY date_received DESC LIMIT 500)
04-23 13:56:16.732 19279 19279 W CanonicalAddressDatabase: Hitting DB on query [ADDRESS]
04-23 13:56:16.769 19279 19279 W CanonicalAddressDatabase: Hitting DB on query [ADDRESS]
04-23 13:56:16.813 19279 19279 W SMSListener: Got SMS broadcast...
04-23 13:56:16.821 19279 19279 W SMSListener: Got SMS broadcast...
04-23 13:56:16.900 19279 19307 W org.smssecure.smssecure.sms.MultipartSmsTransportMessage: Decoded message with version: 3
04-23 13:56:16.900 19279 19307 W MultipartSmsMessageHandler: Processing single part message...
04-23 13:56:16.901 19279 19307 W CanonicalAddressDatabase: Hitting DB on query [ADDRESS]
04-23 13:56:16.942 19279 19307 W MmsSmsDatabase: Executing query: SELECT _id, unique_row_id, body, type, thread_id, address, address_device_id, subject, date_sent, date_received, m_type, msg_box, status, part_count, ct_l, tr_id, m_size, exp, st, date_delivery_received, mismatched_identities, network_failures, transport_type, attachment_id, unique_id, mid, data_size, _data, ct, cl, cd, name, pending_push FROM (SELECT DISTINCT date_sent AS date_sent, date AS date_received, _id, 'SMS::' || _id || '::' || date_sent AS unique_row_id, NULL AS attachment_id, body, read, thread_id, type, address, address_device_id, subject, NULL AS m_type, NULL AS msg_box, status, NULL AS part_count, NULL AS ct_l, NULL AS tr_id, NULL AS m_size, NULL AS exp, NULL AS st, date_delivery_received, mismatched_identities, NULL AS network_failures, 'sms' AS transport_type, NULL AS unique_id, NULL AS mid, NULL AS data_size, NULL AS _data, NULL AS ct, NULL AS cl, NULL AS cd, NULL AS name, NULL AS pending_push FROM sms WHERE (thread_id = 126) UNION ALL SELECT DISTINCT date AS date_sent, date_received AS date_received, mms._id AS _id, 'MMS::' || mms._id || '::' || date AS unique_row_id, part._id AS attachment_id, body, read, thread_id, NULL AS type, address, address_device_id, NULL AS subject, m_type, msg_box, NULL AS status, part_count, ct_l, tr_id, m_size, exp, st, date_delivery_received, mismatched_identities, network_failures, 'mms' AS transport_type, unique_id, NULL AS mid, data_size, NULL AS _data, ct, cl, cd, name, pending_push FROM mms LEFT OUTER JOIN part ON part._id =  (SELECT part._id FROM part WHERE part.mid = mms._id LIMIT 1) WHERE (thread_id = 126) ORDER BY date_received DESC LIMIT 1)
04-23 13:56:16.965 19279 19358 W MmsSmsDatabase: Executing query: SELECT _id, unique_row_id, body, type, thread_id, address, address_device_id, subject, date_sent, date_received, m_type, msg_box, status, part_count, ct_l, tr_id, m_size, exp, st, date_delivery_received, mismatched_identities, network_failures, transport_type, attachment_id, unique_id, mid, data_size, _data, ct, cl, cd, name, pending_push FROM (SELECT DISTINCT date_sent AS date_sent, date AS date_received, _id, 'SMS::' || _id || '::' || date_sent AS unique_row_id, NULL AS attachment_id, body, read, thread_id, type, address, address_device_id, subject, NULL AS m_type, NULL AS msg_box, status, NULL AS part_count, NULL AS ct_l, NULL AS tr_id, NULL AS m_size, NULL AS exp, NULL AS st, date_delivery_received, mismatched_identities, NULL AS network_failures, 'sms' AS transport_type, NULL AS unique_id, NULL AS mid, NULL AS data_size, NULL AS _data, NULL AS ct, NULL AS cl, NULL AS cd, NULL AS name, NULL AS pending_push FROM sms WHERE (thread_id = 126) UNION ALL SELECT DISTINCT date AS date_sent, date_received AS date_received, mms._id AS _id, 'MMS::' || mms._id || '::' || date AS unique_row_id, part._id AS attachment_id, body, read, thread_id, NULL AS type, address, address_device_id, NULL AS subject, m_type, msg_box, NULL AS status, part_count, ct_l, tr_id, m_size, exp, st, date_delivery_received, mismatched_identities, network_failures, 'mms' AS transport_type, unique_id, NULL AS mid, data_size, NULL AS _data, ct, cl, cd, name, pending_push FROM mms LEFT OUTER JOIN part ON part._id =  (SELECT part._id FROM part WHERE part.mid = mms._id LIMIT 1) WHERE (thread_id = 126) ORDER BY date_received DESC LIMIT 500)
04-23 13:56:16.996 19279 19305 W CanonicalAddressDatabase: Hitting DB on query [ADDRESS]
04-23 13:56:17.011 19279 19279 W CanonicalAddressDatabase: Hitting DB on query [ADDRESS]
04-23 13:56:17.012 19279 19307 E MediaPlayer-JNI: JNIMediaPlayerFactory: bIsQCMediaPlayerPresent 0
04-23 13:56:17.012 19279 19307 E MediaPlayer-JNI: JNIMediaPlayerFactory: bIsQCMediaPlayerPresent 0
04-23 13:56:17.028 19279 19279 W CanonicalAddressDatabase: Hitting DB on query [ADDRESS]
04-23 13:56:17.030 19279 19305 W SmsDecryptJob: org.whispersystems.libaxolotl.InvalidMessageException: No valid sessions.
04-23 13:56:17.030 19279 19305 W SmsDecryptJob: 	at org.whispersystems.libaxolotl.SessionCipher.decrypt(SessionCipher.java:287)
04-23 13:56:17.030 19279 19305 W SmsDecryptJob: 	at org.whispersystems.libaxolotl.SessionCipher.decrypt(SessionCipher.java:246)
04-23 13:56:17.030 19279 19305 W SmsDecryptJob: 	at org.whispersystems.libaxolotl.SessionCipher.decrypt(SessionCipher.java:214)
04-23 13:56:17.030 19279 19305 W SmsDecryptJob: 	at org.smssecure.smssecure.crypto.SmsCipher.decrypt(SmsCipher.java:55)
04-23 13:56:17.030 19279 19305 W SmsDecryptJob: 	at org.smssecure.smssecure.jobs.SmsDecryptJob.handleSecureMessage(SmsDecryptJob.java:113)
04-23 13:56:17.030 19279 19305 W SmsDecryptJob: 	at org.smssecure.smssecure.jobs.SmsDecryptJob.onRun(SmsDecryptJob.java:74)
04-23 13:56:17.030 19279 19305 W SmsDecryptJob: 	at org.smssecure.smssecure.jobs.MasterSecretJob.onRun(MasterSecretJob.java:18)
04-23 13:56:17.030 19279 19305 W SmsDecryptJob: 	at org.whispersystems.jobqueue.JobConsumer.runJob(JobConsumer.java:76)
04-23 13:56:17.030 19279 19305 W SmsDecryptJob: 	at org.whispersystems.jobqueue.JobConsumer.run(JobConsumer.java:46)
04-23 13:56:17.030 19279 19305 W SmsDecryptJob: Caused by: org.whispersystems.libaxolotl.InvalidMessageException: Bad Mac!
04-23 13:56:17.030 19279 19305 W SmsDecryptJob: 	at org.whispersystems.libaxolotl.protocol.WhisperMessage.verifyMac(WhisperMessage.java:132)
04-23 13:56:17.030 19279 19305 W SmsDecryptJob: 	at org.whispersystems.libaxolotl.SessionCipher.decrypt(SessionCipher.java:311)
04-23 13:56:17.030 19279 19305 W SmsDecryptJob: 	at org.whispersystems.libaxolotl.SessionCipher.decrypt(SessionCipher.java:265)
04-23 13:56:17.030 19279 19305 W SmsDecryptJob: 	... 8 more
04-23 13:56:17.030 19279 19305 W MessageDatabase: Updating ID: 3331 to base type: 268435456
04-23 13:56:17.040 19279 19307 D MediaPlayer: setSubtitleAnchor in MediaPlayer
04-23 13:56:17.042 19279 19307 D Ringtone: Successfully created local player
04-23 13:56:17.044 19279 19307 E MediaPlayer-JNI: JNIMediaPlayerFactory: bIsQCMediaPlayerPresent 0
04-23 13:56:17.044 19279 19307 E MediaPlayer-JNI: JNIMediaPlayerFactory: bIsQCMediaPlayerPresent 0
04-23 13:56:17.049 19279 19305 W MmsSmsDatabase: Executing query: SELECT _id, unique_row_id, body, type, thread_id, address, address_device_id, subject, date_sent, date_received, m_type, msg_box, status, part_count, ct_l, tr_id, m_size, exp, st, date_delivery_received, mismatched_identities, network_failures, transport_type, attachment_id, unique_id, mid, data_size, _data, ct, cl, cd, name, pending_push FROM (SELECT DISTINCT date_sent AS date_sent, date AS date_received, _id, 'SMS::' || _id || '::' || date_sent AS unique_row_id, NULL AS attachment_id, body, read, thread_id, type, address, address_device_id, subject, NULL AS m_type, NULL AS msg_box, status, NULL AS part_count, NULL AS ct_l, NULL AS tr_id, NULL AS m_size, NULL AS exp, NULL AS st, date_delivery_received, mismatched_identities, NULL AS network_failures, 'sms' AS transport_type, NULL AS unique_id, NULL AS mid, NULL AS data_size, NULL AS _data, NULL AS ct, NULL AS cl, NULL AS cd, NULL AS name, NULL AS pending_push FROM sms WHERE (thread_id = 126) UNION ALL SELECT DISTINCT date AS date_sent, date_received AS date_received, mms._id AS _id, 'MMS::' || mms._id || '::' || date AS unique_row_id, part._id AS attachment_id, body, read, thread_id, NULL AS type, address, address_device_id, NULL AS subject, m_type, msg_box, NULL AS status, part_count, ct_l, tr_id, m_size, exp, st, date_delivery_received, mismatched_identities, network_failures, 'mms' AS transport_type, unique_id, NULL AS mid, data_size, NULL AS _data, ct, cl, cd, name, pending_push FROM mms LEFT OUTER JOIN part ON part._id =  (SELECT part._id FROM part WHERE part.mid = mms._id LIMIT 1) WHERE (thread_id = 126) ORDER BY date_received DESC LIMIT 1)
04-23 13:56:17.069 19279 19304 W SmsSentJob: Got SMS callback: org.smssecure.smssecure.SendReceiveService.DELIVERED_SMS_ACTION , 0
04-23 13:56:17.072 19279 19304 W CanonicalAddressDatabase: Hitting DB on query [ADDRESS]
04-23 13:56:17.073 19279 19413 W MmsSmsDatabase: Executing query: SELECT _id, unique_row_id, body, type, thread_id, address, address_device_id, subject, date_sent, date_received, m_type, msg_box, status, part_count, ct_l, tr_id, m_size, exp, st, date_delivery_received, mismatched_identities, network_failures, transport_type, attachment_id, unique_id, mid, data_size, _data, ct, cl, cd, name, pending_push FROM (SELECT DISTINCT date_sent AS date_sent, date AS date_received, _id, 'SMS::' || _id || '::' || date_sent AS unique_row_id, NULL AS attachment_id, body, read, thread_id, type, address, address_device_id, subject, NULL AS m_type, NULL AS msg_box, status, NULL AS part_count, NULL AS ct_l, NULL AS tr_id, NULL AS m_size, NULL AS exp, NULL AS st, date_delivery_received, mismatched_identities, NULL AS network_failures, 'sms' AS transport_type, NULL AS unique_id, NULL AS mid, NULL AS data_size, NULL AS _data, NULL AS ct, NULL AS cl, NULL AS cd, NULL AS name, NULL AS pending_push FROM sms WHERE (thread_id = 126) UNION ALL SELECT DISTINCT date AS date_sent, date_received AS date_received, mms._id AS _id, 'MMS::' || mms._id || '::' || date AS unique_row_id, part._id AS attachment_id, body, read, thread_id, NULL AS type, address, address_device_id, NULL AS subject, m_type, msg_box, NULL AS status, part_count, ct_l, tr_id, m_size, exp, st, date_delivery_received, mismatched_identities, network_failures, 'mms' AS transport_type, unique_id, NULL AS mid, data_size, NULL AS _data, ct, cl, cd, name, pending_push FROM mms LEFT OUTER JOIN part ON part._id =  (SELECT part._id FROM part WHERE part.mid = mms._id LIMIT 1) WHERE (thread_id = 126) ORDER BY date_received DESC LIMIT 500)
04-23 13:56:17.083 19279 19307 D MediaPlayer: setSubtitleAnchor in MediaPlayer
04-23 13:56:17.085 19279 19304 W MessageDatabase: Updating ID: 3330 to status: 0
04-23 13:56:17.086 19279 19307 D Ringtone: Successfully created local player
04-23 13:56:17.093 19279 19279 W CanonicalAddressDatabase: Hitting DB on query [ADDRESS]
04-23 13:56:17.096 19279 19304 W MmsSmsDatabase: Executing query: SELECT _id, unique_row_id, body, type, thread_id, address, address_device_id, subject, date_sent, date_received, m_type, msg_box, status, part_count, ct_l, tr_id, m_size, exp, st, date_delivery_received, mismatched_identities, network_failures, transport_type, attachment_id, unique_id, mid, data_size, _data, ct, cl, cd, name, pending_push FROM (SELECT DISTINCT date_sent AS date_sent, date AS date_received, _id, 'SMS::' || _id || '::' || date_sent AS unique_row_id, NULL AS attachment_id, body, read, thread_id, type, address, address_device_id, subject, NULL AS m_type, NULL AS msg_box, status, NULL AS part_count, NULL AS ct_l, NULL AS tr_id, NULL AS m_size, NULL AS exp, NULL AS st, date_delivery_received, mismatched_identities, NULL AS network_failures, 'sms' AS transport_type, NULL AS unique_id, NULL AS mid, NULL AS data_size, NULL AS _data, NULL AS ct, NULL AS cl, NULL AS cd, NULL AS name, NULL AS pending_push FROM sms WHERE (thread_id = 126) UNION ALL SELECT DISTINCT date AS date_sent, date_received AS date_received, mms._id AS _id, 'MMS::' || mms._id || '::' || date AS unique_row_id, part._id AS attachment_id, body, read, thread_id, NULL AS type, address, address_device_id, NULL AS subject, m_type, msg_box, NULL AS status, part_count, ct_l, tr_id, m_size, exp, st, date_delivery_received, mismatched_identities, network_failures, 'mms' AS transport_type, unique_id, NULL AS mid, data_size, NULL AS _data, ct, cl, cd, name, pending_push FROM mms LEFT OUTER JOIN part ON part._id =  (SELECT part._id FROM part WHERE part.mid = mms._id LIMIT 1) WHERE (thread_id = 126) ORDER BY date_received DESC LIMIT 1)
04-23 13:56:17.097 19279 19304 W CanonicalAddressDatabase: Hitting DB on query [ADDRESS]
04-23 13:56:17.136 19279 19435 W MmsSmsDatabase: Executing query: SELECT _id, unique_row_id, body, type, thread_id, address, address_device_id, subject, date_sent, date_received, m_type, msg_box, status, part_count, ct_l, tr_id, m_size, exp, st, date_delivery_received, mismatched_identities, network_failures, transport_type, attachment_id, unique_id, mid, data_size, _data, ct, cl, cd, name, pending_push FROM (SELECT DISTINCT date_sent AS date_sent, date AS date_received, _id, 'SMS::' || _id || '::' || date_sent AS unique_row_id, NULL AS attachment_id, body, read, thread_id, type, address, address_device_id, subject, NULL AS m_type, NULL AS msg_box, status, NULL AS part_count, NULL AS ct_l, NULL AS tr_id, NULL AS m_size, NULL AS exp, NULL AS st, date_delivery_received, mismatched_identities, NULL AS network_failures, 'sms' AS transport_type, NULL AS unique_id, NULL AS mid, NULL AS data_size, NULL AS _data, NULL AS ct, NULL AS cl, NULL AS cd, NULL AS name, NULL AS pending_push FROM sms WHERE (thread_id = 126) UNION ALL SELECT DISTINCT date AS date_sent, date_received AS date_received, mms._id AS _id, 'MMS::' || mms._id || '::' || date AS unique_row_id, part._id AS attachment_id, body, read, thread_id, NULL AS type, address, address_device_id, NULL AS subject, m_type, msg_box, NULL AS status, part_count, ct_l, tr_id, m_size, exp, st, date_delivery_received, mismatched_identities, network_failures, 'mms' AS transport_type, unique_id, NULL AS mid, data_size, NULL AS _data, ct, cl, cd, name, pending_push FROM mms LEFT OUTER JOIN part ON part._id =  (SELECT part._id FROM part WHERE part.mid = mms._id LIMIT 1) WHERE (thread_id = 126) ORDER BY date_received DESC LIMIT 500)

**Comment by BastienLQ** [comment]
You can't send to yourself an encrypted message, because keys are the same. If the SIM card knows its phone number, starting a secure session with yourself is blocked.

**Comment by takiainen** [comment]
Well i have managed to start encrypted session with my self before and it succeeded now too. I have tried now also sending sms from another phone to my phone, but I haven't been able to reproduce the issue yet.
