### ISSUE TITLE
MMS trouble after upgrading to Silence

### ISSUE THREAD

**Issue by forteller** [SilenceIM/Silence#392]
Hi. After I found out that I had to change the MMS settings inside of SMSSecure to send/recieve MMS (I did not know that at first, so I didn't understand why it didn't work when I had done everything correct in the system settings. This should be mentioned in the initial welcome screen), I've had no troubles with MMS.

That is until I upgraded to Silence (Well, I didn't send or recieve any MMS in 0.14, only 0.14.1, so I don't know which version broke it). The first time I got an MMS in Silence it just told me that I had to set up the preferences. Why didn't it remember my preferences from before? When I pressed it and changed the preferences nothing happened! The same message about having to set up my preferences/settings was there, and nothing I did got the actual MMS to show. I even tried restarting the phone to be sure. No luck.

This is important, hope you'll be able to fix it soon. Otherwise: Thanks for a great, and important app!

**Comment by BastienLQ** [comment]
Can you attach a debug log right after opening a conversation with a MMS message and tell us what is your carrier?

**Comment by Titome** [comment]
Hi everyone, thanks for your work !

I have the same bug but not since update to silence. I'm french and [Free](http://mobile.free.fr/) is my phone operator.

My log : https://gist.github.com/anonymous/885f0026108dd55fd301726d5642dd70

Tell me if you need more informations.

Thank

**Comment by forteller** [comment]
Thanks for the fast reply @BastienLQ! Here's my log: https://gist.github.com/8a4ab8dd594018dee45f13e9b3bd258f

**Comment by Brains1** [comment]
I am seeing this also. I received my first MMSs since changing carrier. v0.14.1 of Silence. 4 unencrypted MMSs. I selected 'download' (on each one that day), it said 'tap to config settings'. Some of the settings looked ok. I changed the port number from default (blank) to custom and 8799. Returned to the conversation and it continues to say 'tap to config'. No MMSs downloaded or manual 'download' buttons any more.

**Comment by crazy-max** [comment]
Same thing for me i cannot read or send MMS anymore since 0.14

**Comment by g4jc** [comment]
Came here just to say I dido. Affects phones on multiple carriers that I've tested, none are able to receive or send MMS. Removing Silence and using stock Messaging app works fine.

**Comment by Brains1** [comment]
I have now entered all custom values, why would it even be querying the apn db?  I have no download button.

**Comment by BastienLQ** [comment]
@Brains1 I don't understand. Can you provide more details in a new issue, please?
