### ISSUE TITLE
feature to backup ONLY the keys

### ISSUE THREAD

**Issue by zoff99** [SilenceIM/Silence#396]
please add a feature to ONLY backup my key and all other keys.
i don't care about the messages, just need to be able to go on when i switch phone or ROM.

if this is already possible now, i did not find out how to do it.

**Comment by johanw666** [comment]
As said in https://github.com/SilenceIM/Silence/issues/382, this won't be done. Just delete the messages after restore if you want.

**Comment by zoff99** [comment]
what do you mean? what backup option also backups the keys?
the text in the app does never say anything about backing up the keys.

**Comment by johanw666** [comment]
Starting from 0.14.0, there is an encrypted backup option. This backups everything: keys, messages, settings and media.

**Comment by zoff99** [comment]
don't try it with your laptop. try it with any android phone running android 5.1.1 and the included browser

**Comment by ArchangeGabriel** [comment]
@zoff99: Wrong thread?
