### ISSUE TITLE
MMS Trouble

### ISSUE THREAD

**Issue by Brains1** [SilenceIM/Silence#400]
Same initial symtoms as https://github.com/SilenceIM/Silence/issues/392
Now I have 4 MMSs in a conversation which continue to say 'tap to configure settings' despite manually entering custom APN values in Silence.

**Comment by BastienLQ** [comment]
Can you provide a debug log and screenshots?

**Comment by Brains1** [comment]
![screenshot_2016-05-13-15-24-40](https://cloud.githubusercontent.com/assets/19285798/15251944/b25284b6-1923-11e6-85e2-7cb46b699ead.png)
![screenshot_2016-05-13-15-23-54](https://cloud.githubusercontent.com/assets/19285798/15251949/b6f8f5e0-1923-11e6-9d46-26c77f914d8d.png)
Log is https://gist.github.com/anonymous/be2ff2c519f0dfacde9ac45fa0918102

**Comment by Brains1** [comment]
If you got any thoughts be quick they expire tomorrow ! :)
