### ISSUE TITLE
Possible issue sending simple SMS to iOS devices

### ISSUE THREAD

**Issue by cjeanneret** [SilenceIM/Silence#410]
Hello,

I seem to have an issue while sending unencrypted SMS to iOS devices (iPhone 4 mostly). It's a bit annoying, as most of my family has such a device and therefore are unable to get any SMS from me — I usually can use Threema, but in some case this isn't an option…

Am I the only one with such an issue? Is there a way to know a bit more about what's happening?

Thanks for your feedback/remarks.

Cheers,

C.

**Comment by johanw666** [comment]
No, I sometimes send unencrypted sms to iPhones (4s and 5s), and they to me. Silence has no problems sending or receiving them.

What is the exact problem? Don't they arrive at all?

**Comment by cjeanneret** [comment]
Me again, sorry for the delay.

the issue was:
* dual-sim phone (cyrus)
* one of the SIM was deactivated
* even with phone set to send SMS through the other SIM, Silence didn't send the SMS until I switched the second SIM on…

I'll dig into that, I close this issue as not correctly detected/explained.
