### ISSUE TITLE
MMS does not work only in Silence app in LG G2 when the device is using KT LTE network w/ VoLTE

### ISSUE THREAD

**Issue by Mnkai** [SilenceIM/Silence#411]
While KT IMS exists in CM APN list - line 3026 of https://github.com/SilenceIM/Silence/blob/master/scripts/apntool/apnlists/cyanogenmod.xml - it does not seems to exist in apns.db, and I suspect this causes some devices with KT carrier w/ IMS MMS setting failing on receiving/sending mms.

Affected device is LG G2, and this device is running Android 4.4. Symptoms are:

1. Fail to receive/send MMS in Silence app, but able to receive/send MMS messages in stock messaging app when the device is operating in LTE mode (using VoLTE).
2. When the device is operating in 3G mode, MMS receiving also works in Silence app.
3. SMS receiving works fine in every operating mode.

Interestingly, other device (Nexus 5X) which is also operating in VoLTE mode actually has different default APN setting from G2. And from that device, MMS is working fine with Silence.

```
CM default APN setting / 5X default APN setting (Running OMNI) :
 - lte.ktfwing.com, default,mms,supl,fota,cbs, mmsc: http://mmsc.ktfwing.com:9082
 - ims.ktfwing.com, ims
 
G2 default APN setting: 
 - lte150.ktfwing.com, default,supl,fota,cbs
 - ims.ktfwing.com, ims,mms, mmsc: http://mmsc.ktfwing.com:9082
```
 
Manually changing setting of G2's APN in system's setting to CM/5X APN setting does not work.

**Comment by BastienLQ** [comment]
KT IMS is not in `apns.db` because it is not an MMS APN. Silence do not read phone's APN settings but directly asked the user to enter manual MMS settings if no entry is found in `apns.db`. Closing this issue in favor of #430.
