### ISSUE TITLE
"Blocked contacts"

### ISSUE THREAD

**Issue by Grah96** [SilenceIM/Silence#414]
Under Privacy settings there is an option called "blocked contacts", but there is no menu, it's just a blank page, no settings. So how do I use this option? It would be very useful to be able to block some contacts/numbers.
Thanks

**Comment by pR0Ps** [comment]
That page shows a list of currently blocked contacts. If you haven't blocked anyone, there won't be anything there.

To block a contact, go into the conversation and tap on the name/number in the top left. In the contact details screen that appears, tap the "Block" option.

After doing that, the contact will show up in the "Blocked contacts" page. Tapping it will open the same contact details screen where you can unblock the contact.

**Comment by Grah96** [comment]
Brilliant, thanks.
