### ISSUE TITLE
Time indication on messages

### ISSUE THREAD

**Issue by Dugueperoux** [SilenceIM/Silence#416]
For personal reasons, I currently like to set my smartphone clock 5 minutes in advance compared to the real clock (which means my clock shows 00:05 when it is actually 00:00… in the following, I'll distinguish "personal" clock and "real" clock). 
The messages I send are shown with my personal clock, while the messages I receive are shown with what looks to be the real clock (maybe the sender clock ? it would sound more logical…).

The good point is that the order is respected, which means that I sometimes have something like this, in that order : 
(my message) 00:05
(the answer to my message) 00:02

So far, so good, even if it is quite weird to see that for the first time. However, the discussions are sorted according to the time of the last message, and then, it becomes confusing : I have sometimes sent a lot of messages (to many people) within a very short amount of time, and then, people who answer me are automatically set at then end of these messages. 
Exemple : 
I sent "message" to 10 people at 00:00 (real time)
All messages are counted as 00:05 because of personal time.
Someone answers me (or send me a message) at 00:02 (real time)
The discussion will be the last of the 10.

I don't know how hard it would be, would it be possible to have the received messages set with the "personal" time, instead of "real/other people" time ?

Thanks a lot, and apologies for poor English !

**Comment by slim** [comment]
I have the same issue. It's annoying : sometimes my phone clock gets reset and I don't notice. So messages I receive actually **disappear**. 

In reality what happens is : 

1. the message is dated with a date in the past something like 2010-01-01
2. the message is inserted a the beginning of the long message thread of the sender 

even though I now know that they did not disappear, it's really annoying to scroll till the beginning of a long thread

**Comment by pR0Ps** [comment]
In Settings -> SMS and MMS there is an option called "Show sent time". When enabled, this option will use the time the recipient sent the message as the received time. If disabled, the sent time will be set to whatever your current time was when it was received.

Disabling this option should fix your issues.

Please reopen if it doesn't.

**Comment by slim** [comment]
That won't solve my problem. Since my problem happens when my current time is wrong when the message was received. There should be an ordering of the messages not based on time.

**Comment by pR0Ps** [comment]
When sending messages, we have to use whatever time the system reports because there is no other option. On receiving messages we can use the timestamp that the message reports (sent time option enabled) or we can use the time the system reports (sent time option disabled). There aren't any other viable options.

Honestly, the fact that your clock is periodically resetting back to 2010 is the real problem, this is just a symptom.
