### ISSUE TITLE
Decryption broken

### ISSUE THREAD

**Issue by davidhedlund** [SilenceIM/Silence#417]
Silence 0.14.3 sometimes do not decrypt messages for me. It has happened on several occasions.

Test case: Samsung Galaxy S6, Messaging set to standard (not Silence)

**Comment by pR0Ps** [comment]
Please explain in more detail. What Android version? What phone? In what
situation does the bug occur (on reboot/immediately after receiving the
message/other)? Always the same contact? Long messages? Short messages? Is
it showing ciphertext, an error message, or something else? Does it just
occur in the text of a notification or is it in the app as well?

In addition, please submit a debug log (Settings -> Advanced -> Submit log)
as soon as see the problem happening.

**Comment by davidhedlund** [comment]
[mylabel:important](https://github.com/search?utf8=%E2%9C%93&q=commenter%3Adavidhedlund+%22mylabel%3Aimportant%22+in%3Acomments&type=Issues&ref=searchresults)

**Comment by davidhedlund** [comment]
[mylabel:help wanted](https://github.com/search?utf8=%E2%9C%93&q=commenter%3Adavidhedlund+%22mylabel%3Ahelp wanted%22+in%3Acomments&type=Issues&ref=searchresults)
