### ISSUE TITLE
Toolbar icon removal

### ISSUE THREAD

**Issue by Woodzrul** [SilenceIM/Silence#418]
Hello

More of a question than an issue. If I want to remove the Silence icon from the top left toolbar on the main screen, which .xml file would I need to amend? I have done some research though struggling to get my coding correct. I am a noob who is trying to learn.

Your help is greatly appreciated.

Thanks

![screenshot_20160615-163842](https://cloud.githubusercontent.com/assets/15090471/16086613/123ffc38-3318-11e6-98b0-3d83637cb9a9.png)

**Comment by pR0Ps** [comment]
The ActionBar styles are configured here:
https://github.com/SilenceIM/Silence/blob/0ca909dd8af0d519bc607d2b71a76d8ad8f67106/res/values/styles.xml#L28
. The icon is referenced to in there as "@drawable/actionbar_icon"

**Comment by Woodzrul** [comment]
Very kind. I shall have a play later today.
