### ISSUE TITLE
Duplicate messages

### ISSUE THREAD

**Issue by ClubWDW** [SilenceIM/Silence#420]
Some users of Silence are sending me a duplicate of every message they send at the same time as the original setting. Am I missing something in a setting?

**Comment by ClubWDW** [comment]
Quick update...it appears to only happen when sending from Samsung...FYI...

**Comment by ClubWDW** [comment]
Update 2: When anybody sends to a group message, if there has been a previous message from the sender, the new message will show up in the group message, but then the last individual message sent from that person goes from read back to unread. For what it is worth, I am on CM13 on a Nexus 6.

**Comment by ClubWDW** [comment]
Update 3: I have a friend running CM13 on Nexus 6P. Had one of my Samsung friends send a message...no duplicate message.....really perplexed by this.

**Comment by ClubWDW** [comment]
Update 4: Okay.New info. Messages that are sent as part of an MMS from Samsung phones, do not produce the "duplicate message" error. Messages that are 64 characters or over, do not produce the "duplicate message" error. Message that are less than 64 characters do produce the "duplicate message" error.

**Comment by ClubWDW** [comment]
Is anyone seeing this thread? If so, please comment. I don't want to waste dev's time if not. (Grin)

**Comment by BastienLQ** [comment]
A lot of things can explain duplicate messages (mostly the phone's firmware on unreliable networks), but none of these can be fixed, because it would require to patch the Android SMS API.
