### ISSUE TITLE
[Feature Request] - SMS Scheduler

### ISSUE THREAD

**Issue by darryl-grennan** [SilenceIM/Silence#421]
Hi folks!

I just wanted to make the suggestion that it would be really handy to have the functionality of "SMS Scheduler".  It causes the messenger to delay/set (on-device) when you prepared message is to be sent.  Allows for recurrences as well.

**Comment by ClubWDW** [comment]
+1

**Comment by pR0Ps** [comment]
Closing as dupe of #314
