### ISSUE TITLE
libcurve25519

### ISSUE THREAD

**Issue by herbert777** [SilenceIM/Silence#426]
Hi!
I have built Silence from source, fine.
Then I downloaded libcurve25519's source and built its jni folder with ndk, fine, but the resulting file is bigger than the one you use in Silence (167900 b whereas yours is 135228 b). When I use the libcurve that I compiled Silence works as expected, it opens and can send/receive sms', but I d like to be sure that I didn t mess anything, specially the overall security/encryption stuff.
So, 2 different libcurve, I m a bit lost...
Maybe your file is smaller because you used only part of its source, with the ABI options?
The thing is that I searched and I searched in Silence's source but I could t find anywhere how to build libcurve the Silence way.
Would you mind sharing the way you did it?
I add that I m pretty new to this whole building process, so please bear with me if my question is stupid or noobish...
FYI, I downloaded libcurve's source from here, I guess that s the right place:-) :
https://github.com/WhisperSystems/curve25519-java
Thanks in advance!

**Comment by pR0Ps** [comment]
We're probably just using an older version or something. If you take a look in the `build.gradle` file in the root of the repo, you'll see `org.whispersystems:curve25519` in there. It's being built as a dependency for another dependency which probably just hasn't updated the version it uses yet. We honestly haven't touched it since forking from Signal-Android.

**Comment by herbert777** [comment]
Sorry for the late reply, I have been busy...
I knew about `org.whispersystems:curve25519`, the files are in my local depedencies folder (curve25519-java and curve25519-android), but I hadn t realised that the reason for the size difference was an outdated version used while compiling silence.
Thank you for your reply:-)
