### ISSUE TITLE
Get asked for a SIM in dual SIM case

### ISSUE THREAD

**Issue by artem-sidorenko** [SilenceIM/Silence#428]
There are some mobiles with dual sim support (e.g. BQ Aquaris X5, Wileyfox Swift etc). Native SMS app provides settings and 

 1. a possibility to choose the SIM card, which should be used for SMS generally
 2. or to be asked by each SMS (tested on Cyanogenmod 13.0)

Option 1. works with Silense as well (an you can see the source/target SIM), but there is no simple way to get asked for each SMS like on the native SMS app

**Comment by pR0Ps** [comment]
@artem-sidorenko: If you long press on the send button you should see options to send with different SIM cards. The app should remember which SIM you used last and default to it for next time as well.

Feel free to reopen if this isn't working for you.

**Comment by rfc2822** [comment]
Wow… this is amazing. I didn't know that Silence was able to send to the different SIMs until I have found that. Maybe it could be mentioned somewhere in the app or on the home page (FAQ?).

(And thanks für Silence!)

**Comment by Chewie9999** [comment]
I just found this as I thought it was a bug that I couldn't find the option mentioned in the features - I was using the google settings to swap between the sims (my default messaging app allows you to choose after sending)!
As silence seems to know which SIM the message is received from (it's listed per message in the conversation), would it be possible to make it default to reply using the same SIM unless you long press to choose an alternative?

Great app btw :)
