### ISSUE TITLE
Can't send any SMS

### ISSUE THREAD

**Issue by TakerMc** [SilenceIM/Silence#431]
As explained in the title when i try to send a message it doesn't work.

Debug log: https://gist.github.com/anonymous/fbba2a08d8726382ca1823d61c7ed475

**Comment by BastienLQ** [comment]
Is your SIM card put in slot 2 of your phone? Multi-SIM support is available on Android 5.1+ only and phones with an earlier version of Android can use the first slot only.

**Comment by TakerMc** [comment]
Yes, my SIM card is in the second slot. The first one doesn't work anymore
