### ISSUE TITLE
为什么我不能Fork 代码

### ISSUE THREAD

**Issue by hkzws** [SilenceIM/Silence#433]
我有个想法,想添加一个功能,但是代码下载下来不能用,一直编译不能通过,这是为什么

**Comment by pR0Ps** [comment]
Google translate output:
Why can not I Fork Code?

I have an idea and want to add a feature , but the code can not be downloaded , has not compile , which is why

**Comment by BastienLQ** [comment]
Hi @hkzws,

Please use English here.
See https://github.com/SilenceIM/Silence/blob/master/BUILDING.md for building instructions.
