### ISSUE TITLE
How to convert the exported plaintext backup to a readable .txt form?

### ISSUE THREAD

**Issue by gerg5c42g542g2c54g52c** [SilenceIM/Silence#438]
It's an .xml file which is very hard to read. I'd like to read my backup in a normal text editor, how do I convert it to such form?

**Comment by pR0Ps** [comment]
XML is just structured textual data, you can extract the bits of data you
want fairly easily from it.

Option 1 (minimal coding required): Run the file through some sort of XML
parser and pull out the fields you want into a plain text document. See
http://stackoverflow.com/questions/1912434/how-do-i-parse-xml-in-python for
an example.
Option 2 (no coding required): Use a freely available XML to CSV converter,
open the CSV file up in a spreadsheet program, delete the data you don't
want, then save or copy/paste the remaining data into a text file.

**Comment by whiver** [comment]
Hi all,

I tried to parse my exported XML file, but it seems to be badly encoded.
I have some unknown characters in the file, that mainly seem to be smileys in the original SMS. For example the parser doesn't recognize the character `&#55356;` in this message (in French), extracted from my Silence backup:

```
Helloooo, un weekend pluvieux qui s&apos;annonce, mais qui s&apos;en soucie ?
☂&#10;&#55356;&#57255; ⛪&#65039;&#10;Ce soir, un concert pas comme les autres : électro, son
et lumière à l&apos;Eglise Saint-Merry : http://hij.am/2wy5u&#10;&#55357;&#56567;
&#55356;&#57261;&#10;Demain, exposition sur Herb Ritts, un virtuose de la photo de mode :
http://hij.am/d9bz7&#10;&#55357;&#57035;&#55356;&#57253;&#10;Et dimanche, c&apos;est
l&apos;anniversaire de James Gandolfini (RIP), l&apos;acteur principal de la série Soprano. Un bon
prétexte pour se (re)faire quelques saisons dans son lit :)&#10;Profite bien !
```  
Is it a bug or is this behaviour compliant to the way SMS backup & restore handles the backups?
In each case, how can I parse it? It seems that even the project of backup parser that I mentioned before is not able to read the Silence backup...

**Comment by ArchangeGabriel** [comment]
@whiver That is just HTML encoding, nothing wrong here.

**Comment by whiver** [comment]
No it is not, since the character is invalid.
I tried exporting my conversation using the SMS Backup & Restore app and it works. I mean I can read the XML file in Firefox, for example, but I can't with the Silence backup.

If I open the file with Firefox, I have the following error:
![image](https://user-images.githubusercontent.com/394565/35247923-6c4d0054-ffcc-11e7-86e1-04c07eef3214.png)

I could translate it by "XML analysis error: reference to an unknown character number".

**Comment by ArchangeGabriel** [comment]
Not unknown, but invalid character number. Those are indeed strange character number, even though they do exist (https://unicode-table.com/en/D83D/ and https://unicode-table.com/en/DE0E/). Do you know what character they are replacing?

**Comment by whiver** [comment]
Yes indeed. In fact this character and the following one are replacing one character which was a smiley (I can find which one if you really need it :p). However this character is not the only one that was invalid, if I remove it there are others, and different ones, in the other message, but all are replacing smileys in the original message.

It's like if the unicode character of the smiley was split in two invalid character. I would be tempted to think that the first character corresponds to the first byte of the smiley and the second invalid character corresponds to the second byte. Is it not something like a conversion from UTF-16 to UTF-8 ? I am not an Unicode expert so it is only a supposition.

**Comment by whiver** [comment]
Ok I got it, it was this smiley: 😎 
But in my first message it was 🎧  I think.

**Comment by whiver** [comment]
I checked the unicode codes and indeed, it seems that the original emojis have been converted into 2 "surrogates" characters. Using this online tool, I managed to get back my original emoji: http://www.russellcottrell.com/greek/utilities/SurrogatePairCalculator.htm

So my question is: why the XML is still invalid, isn't it an encoding mistake that makes the Silence XML writer produce surrogates codes?
