### ISSUE TITLE
Turning off the screen with Silence open will make android crash.

### ISSUE THREAD

**Issue by az35as6** [SilenceIM/Silence#443]
Hello,
First I wanna say that I don't have a very popular phone, witch is a Wiko Birdy running the stock rom android 4.4.2 rooted and the last updated version of Silence from F-droid, the 0.14.3.
Also, i am not a native english speaker, and i believe my writing will be fairly bad. I apologize.

When i leave Silence open and try to switch off the screen, android won't stand it and reboot right after a few seconds. The crash come just after i press the lock button, and switch off the screen without the usual animation. 
I had doubt about the fact that the problem was coming from Silence only, since it was a very OS-related bug, but the thing is that Silence is the only app which made crash my phone in this strange way.

Here is the relevant preferences Silence is currently running with :
```
---SMS & MMS---
Default SMS App : Silence
Show sent time : Off
SMS delivery reports : Off
Wifi Calling : Off
Manual MMS settings : Yes
---Notifications---
Notifications : On
Sound : default ringtone
Vibrate : On
Led Color : Green
Led blink pattern : Normal
In-conversation notification : On
Repeat Alerts : Never
display on notifications : Name & Message
---Privacy---
Passphrase : Off
screen security : On
Blocked Contacts : None
---Appearance---
Theme : Dark
Language : Default (fr)
---Chats & media---
Auto-retrieve : On
roaming auto-retrieve : On
Delete Old Messages : Off
---Advanced---
keyboard options : Show enter key
disable emoji drawer : off
Complete key exchanges : yes
```

Here the info i've found in the debug log :

```
Device  : WIKO BIRDY 
Android : 4.4.2 (14, ALPS.KK1.MP3.V1)
 Memory  : 16M (16.47% free, 128M max) 
Memclass: 128 
OS Host : H02-VM1 
App     : Silence 0.14.3
  --------- beginning of /dev/log/main 
W/dalvikvm( 4550): VFY: unable to resolve virtual method 483: Landroid/content/res/
TypedArray;.getChangingConfigurations ()I 
W/dalvikvm( 4550): VFY: unable to resolve virtual method 505: Landroid/content/res/
TypedArray;.getType (I)I 
W/dalvikvm( 4550): VFY: unable to resolve virtual method 11066: Landroid/view/
Window;.setStatusBarColor (I)V
 W/dalvikvm( 4550): VFY: unable to resolve virtual method 11066: Landroid/view/
Window;.setStatusBarColor (I)V E/dalvikvm( 4550): Could not find class 'android.media.AudioAttributes$Builder', referenced from method
org.smssecure.smssecure.notifications.MessageNotifier.sendInThreadNotification 
W/dalvikvm( 4550): VFY: unable to resolve new-instance 154 (Landroid/media/AudioAttributes$Builder;) in Lorg/smssecure/smssecure/notifications/MessageNotifier; 
E/        ( 4550): appName=org.smssecure.smssecure, acAppName=/system/bin/surfaceflinger 
E/        ( 4550): 0 
E/        ( 4550): appName=org.smssecure.smssecure, acAppName=/system/bin/surfaceflinger 
E/        ( 4550): 0 W/dalvikvm( 4550): VFY: unable to resolve virtual method 446: Landroid/content/res/
Resources;.getDrawable (ILandroid/content/res/Resources$Theme;)Landroid/graphics/drawable/Drawable; 
W/dalvikvm( 4550): VFY: unable to resolve virtual method 448: Landroid/content/res/Resources;
.getDrawableForDensity (IILandroid/content/res/Resources$Theme;)Landroid/graphics/drawable/Drawable; 
E/dalvikvm( 4550): Could not find class 'android.graphics.drawable.RippleDrawable', referenced from method org.smssecure.smssecure.ConversationListItem.setRippleColor 
W/dalvikvm( 4550): VFY: unable to resolve check-cast 146 (Landroid/graphics/drawable/RippleDrawable;) in Lorg/smssecure/smssecure/ConversationListItem; 
D/skia    ( 4550): jpeg_decoder mode 0, config 4, w 96, h 96, sample 1, bsLength 0!! 
D/skia    ( 4550): jpeg_decoder mode 1, config 4, w 96, h 96, sample 1, bsLength 0!! 
D/skia    ( 4550): jpeg_decoder mode 0, config 4, w 96, h 96, sample 1, bsLength 0!! 
D/skia    ( 4550): jpeg_decoder mode 1, config 4, w 96, h 96, sample 1, bsLength 0!! 
W/dalvikvm( 4550): VFY: unable to resolve direct method 1045: Landroid/preference/CheckBoxPreference;.<init> (Landroid/content/Context;Landroid/util/AttributeSet;II)V
W/dalvikvm( 4550): VFY: unable to resolve virtual method 11210: Landroid/widget/CompoundButton;.drawableHotspotChanged (FF)V
```

Anyway, thanks for your work, and i wish you guys good luck for the continuation.

**Comment by aviallon** [comment]
Hello @az35as6, I'm not the maintainer of this app, but if you really want to leave those bugs, you can try to install a custom ROM. Just tell me what is your phone model (I mean the _model_ and not the name) by going in Settings->About phone->Phone model and then I'll guide you to install something like CyanogenMod if it exists.

**Comment by az35as6** [comment]
Hi @aviallon, and thanks for your friendly help. Here is my phone specs in plain text.
https://ghostbin.com/paste/jq5wq

I had previously looked for a compatible version of CM (with the CM installer from F-droid), and the answer was negative. I don't know for the other distributions, but I guessed that if the biggest alternative didn't know about my phone, the other won't be as well. So, if you do find one I would be quite surprised and grateful.

**Comment by BastienLQ** [comment]
Does this crash occur if screen security is disabled?

**Comment by az35as6** [comment]
I would like to update my request by announcing that another app (Wickr) made the same issue. 
I no longer believe this problem would be caused by Silence, so this issue can be closed.
Thanks for your help anyway !
