### ISSUE TITLE
Silence is silent for encrypted messages

### ISSUE THREAD

**Issue by asaladin** [SilenceIM/Silence#447]
I have no idea why I get this problem, but when I receive an encrypted message my phone only vibrates while with a plain text sms I have both a vibration and a sound notification. 
I tried with about 30 messages of each kind (encrypted or not), I could reproduce this issue every time.

I tried rebooting the phone then reinstalling the app, with no success. 

This is on android 7 beta (build NRD90M, on a nexus 5X), while another phone (also nexus 5X) on android 6 with the same Silence app (0.14.3, build 3790d80) does not have this problem.

**Comment by asaladin** [comment]
The second phone just got upgraded to Android 7 (non beta, same build number). Same problem now on both phones.

Also Silence needs to be in the background for this problem to manifest. 

So to recap:

Android <7  => ok
Android 7 + Silence in foreground => ok
Android 7 + Silence in background + plain text => ok
Android 7 + background + encrypted sms => no sound notification, small vibration.

**Comment by Seth-Johnson** [comment]
I am also having this issue on a 7.0 Nexus 5X. It makes silence almost unusable.

**Comment by asaladin** [comment]
I updated one phone to andorid 7.1. Same problem unfortunately.
