### ISSUE TITLE
ShellMS Support

### ISSUE THREAD

**Issue by ThePreviousOne** [SilenceIM/Silence#455]
I used to use https://github.com/try2codesecure/ShellMS as my messaging app a lot. To have this work with Silence would be amazing IMO

**Comment by pR0Ps** [comment]
I had a look. It seems like ShellMS sends the message itself so we wouldn't be able to hook into it in anyway.

**Comment by ThePreviousOne** [comment]
A few days ago I started work on this myself, going the other way. Would it be possible, or would it be possible to make it possible, to access the "Keyring"?
