### ISSUE TITLE
Bluetooth 

### ISSUE THREAD

**Issue by AlphaOmega3** [SilenceIM/Silence#456]
Mmh, it's possible add an ability to send encrypted SMS/MMS or other via Bluetooth like a Walkie-Talkie??

**Comment by johanw666** [comment]
No, that would by definition not be SMS or MMS. There exist chat programs who use bluetooth, like https://play.google.com/store/apps/details?id=org.jastrzab.serwer.bluetooth&hl=en, but I fail to see the use. If you're that close you can just talk.

**Comment by pR0Ps** [comment]
Closing as out of scope
