### ISSUE TITLE
SMS more than about 140 characters never received when I am on another country (roaming)

### ISSUE THREAD

**Issue by 2Belette** [SilenceIM/Silence#465]
I realized yesterday that almost all my SMS was not received to different contact and easy to reproduce is my SMS is around > 140 characters...

Anyone has the same issue ? Don't know if it is roaming related ?  (data roaming is activated anyway in case Silence transform multiple SMS to MMS?)

EDIT : forgot to mention that I am sending/receving MMS right
EDIT2: going back at home and same issue!

I also realized that randomly my correspondant dont receive my message 
I also realized that deleting a special character "ç" in the message and sending it again and it works 
Putting again the same character and it was never received 
Puting the "ç" character on another message and it is working so it is not 100% corelated 

No one experiment some issues like this ?

**Comment by BastienLQ** [comment]
I need a debug log to help you.

**Comment by 2Belette** [comment]
Excuse for the this it was a custom ROM issue, closing it
