### ISSUE TITLE
We see multiple encrypted block when the message is too long

### ISSUE THREAD

**Issue by cirdebit** [SilenceIM/Silence#469]
When my friend is sending (or me) me a very long message (at least 2x160 characters - we don't really know) we see multiple encrypted block like in these pictures instead of the real message (the encrypted session is established etc, everything else is ok) :

http://img4.hostingpics.net/pics/425835481.png
http://img4.hostingpics.net/pics/359442422.png

**Comment by ArchangeGabriel** [comment]
Just an advise, you should try harder if you want to obfuscate things. :) Everything you’ve hided is readable (and knowing it’s 11 h 51, that you’re french or that on 11 h 02 you’ve sent « Bah copie et colle-là ici alors » — I’ve fixed the eventual typo — are not my biggest concerns regarding this if you know what I mean). :(

A flat rectangle over what you want to hide is probably easier, faster and better. ;)

Regarding your issue: does this happen with other contacts (if you have any other using Silence)? @BastienLQ/@pR0Ps will probably need logs to debug this, but be sure if you post them online to clean them before, else I suppose you could send them to support@silence.im.

**Comment by qwertygc** [comment]
I am the same error if the secure mode is enable (obviously the contact use silence)
