### ISSUE TITLE
Feature request: Add the support of Sailfish OS

### ISSUE THREAD

**Issue by HumanG33k** [SilenceIM/Silence#472]
Everything is in the title.

There is less alternative to Android with google code.
Maybe it's a good idea to add the support of sailfish OS. 

For the moment the app start but can't import and crash if we try to use it.

**Comment by pR0Ps** [comment]
Without having looked into Sailfish (and not promising anything), if were going to even start looking at it, we would need a log showing why it's crashing.

**Comment by BastienLQ** [comment]
SailfishOS API for Android apps is very, very limited. For example, Silence will not be able to get contacts list in SailfishOS. This is a blocking issue for a daily use and we won't focus on this OS for now.

**Comment by marmistrz** [comment]
Well, I guess it would make more sense to create a native app than to adapt the Android one.
