### ISSUE TITLE
"Unfortunately, System UI has stopped" when accessing Recent Apps from within Silence

### ISSUE THREAD

**Issue by ThornedRose** [SilenceIM/Silence#474]
**Issue:** When in Silence, pushing the phone's hamburger menu to bring up Recent Apps, causes the system ui to crash. Silence stays focused. Pushing the menu button again will cause the system ui to crash again.
To avoid this, I push the phone's hardware home button to go back to the home screen and then push the menu button to bring up recent apps.
Signal (also installed) displays the same behaviour.
Can't find anything like this in other issues or on Signal's issues

**Device:** Samsung Galaxy Note3 (SM-N9005)*
**Android:** 6.0.1*
**Silence:** v0.14.3, build ID 3790d80

_* This may or may not be problematic. While my phone is a Note3, I am running a ported Note7 (SM-N930F) ROM. Specifically Phronesis N930FXXU1BPH6.v4. The kernel is lsskernel version hlte-eur-3.7UX. If you need any more info, let me know._

**App state:** No relevant settings that I can ascertain.

**Debug log:** http://pastebin.com/GH5DzrX8

**Comment by BastienLQ** [comment]
This isn't a Silence issue. I suspect your ROM can't deal with screen protection.
