### ISSUE TITLE
SMS count issues

### ISSUE THREAD

**Issue by rugk** [SilenceIM/Silence#479]
### Bug description

I use Call Meter 3G to collect various statistics.
Now at least when sending encrypted SMS messages I do not see them to be count.
Could it be that silence does not led them count?

### How to reproduce
- install all apps
- set as primary SMS app
- send encrypted sms

**Actual result:** call meter does not show a new send SMS
**Expected result:** let other apps count all messages

### Device info
- Android version: CM 13 based on Android 6
- Silence version and build ID: 0.14.3

**Comment by johanw666** [comment]
That program claims to require sms access to count the number of messages, so I assume it does that by accessing the sms database. Because Silence and Signal don't use this database but use their won encrypted storage this method will not work.

**Comment by pR0Ps** [comment]
@johanw666 is correct - this isn't something we can fix. Something that may mitigate this would be the implementation of #145
