### ISSUE TITLE
How about Markov-chained cipher ?

### ISSUE THREAD

**Issue by az35as6** [SilenceIM/Silence#480]
Hello everyone, 
I've recently saw video and project talking about this  way encrypting text with text, witch make the upcoming results less suspicious.
[https://www.youtube.com/watch?v=5_YBp36mf_g](url)
Here is a recent video talking about a github project : [https://github.com/linenoise/asemica](url)
I believe adding this feature would be quite useful.

**Comment by pR0Ps** [comment]
We're not too concerned with making comms less suspicious, just in making them secure.
