### ISSUE TITLE
The Notifications appear only if I open the application

### ISSUE THREAD

**Issue by MrGlloq** [SilenceIM/Silence#485]
### Bug description

Since the update v0.14.4
The Notifications appear only if I open the application between two encrypted conversations
Notifications appear if the sender does not encrypt.
With an unencrypted message, One notification appears at the arrival of the message and another at the opening of Silence.
I am never warned of the arrival of a new message.
Before, never had this problem.

### Device info
- Device: Nexus 5
- Android version: 6.0.1
- Silence version and build ID: Cyanogenmod 13.0.20160820-SNAPSHOT-ZNH5YAO0J2-hammerhead
Kernel : 3.4.0-g1070bba

Same Problem with Samsung Galaxy A3 2016 (A310FZKA) original ROM.

**Comment by BastienLQ** [comment]
Can you still reproduce this issue with Silence v0.14.5?

**Comment by MrGlloq** [comment]
Hi,
I do the new update and try.
For information, no light notification AND no sound notification, not 
only lightsnotifications
Well done for your reactivity.

**Comment by MrGlloq** [comment]
After update 2 devices (Nexus and Samsung) v0.14.5

Notification Sound or Lights not appear if Silence is Locked by password.

If I enter the password,Notifications appear immediately.

Regards

**Comment by BastienLQ** [comment]
Got it. I'm working on this.

**Comment by MrGlloq** [comment]
Ok, available for feedback
