### ISSUE TITLE
Unencrypted notification displayed twice

### ISSUE THREAD

**Issue by canou** [SilenceIM/Silence#490]
Since v0.14.4 (and further versions), whenever I receive a message, the notification appears twice.
One time when receiving a message, and a second time when unlocking Silence.
I can't confirm behavior for encrypted messages as I don't have any.

BTW, I'm running latest CM 14.1 nightly for my Moto G (falcon).

**Comment by ArchangeGabriel** [comment]
Yes, they have been a succession of changes regarding notification. In your case, see https://github.com/SilenceIM/Silence/pull/488.

**Comment by canou** [comment]
Indeed, I'm aware of the recent work about notifications (and why I waited until I could use v0.14.6 before reporting the issue). In my case, this is slightly different, as this is happening in unencrypted conversations.

**Comment by ArchangeGabriel** [comment]
Oh, I missed that essential part of your message. Then it will wait for @BastienLQ to look at it. Seems the notification issues chain is not yet over.

**Comment by jpierre03** [comment]
Same issue here for both secure and plain text messages.
Notifications are delivered on message reception AND after silence passphrase validation
* Silence 0.14.5.
* compilation id : fd8f2a2

**Comment by canou** [comment]
Sadly, I can confirm that i still encounter this behavior with v0.14.7.
May a debug log be useful ?
Otherwise I'll try to find some time to grab the source and track the issue.

**Comment by BastienLQ** [comment]
@canou I can't reproduce this bug on my side (Android 7). Can you post a screenshot and details on your phone, please?

**Comment by canou** [comment]
Here you have :

![screenshot_20161229-153934-2](https://cloud.githubusercontent.com/assets/5215951/21553681/f9a894ea-ce09-11e6-9960-a983c7927457.png)

This is what I have when unlocking Silence. I already got the first notification, then unlock my phone, go to Silence, unlock Silence, and here it is again, buzzing as well. There's only one message (from the convo beaneath the notification), this is not another message recieved meanwhile.

I tried wiping Silence cache then restarting the phone, with no luck. My phone is a Moto G (falcon, X1032) running CyanogenMod 14.1-20161223 (so Android 7.1.1). If it has something to do with it, Hide notifications sensitive content option in System Setting is on, as well as all Silence privacy options. (Well, at least the no screenshot option has nothing to do with it, otherwise I couldn't show you this :-) )

**Comment by canou** [comment]
I was able to reproduce this behavior using Silence master branch, running via Android Studio on AVD Nexus 5, API 25.
I'm still learning Android development as well as how Silence works (and is supposed to) but here's what I learned so far :

Looks like as `SmsDecryptJob` is called when unlocking Silence, it's `onRun` method calls `messageNotifier.updateNotification` setting `vibrate` to `false` and flags to `MNF_DEFAULTS`.

Then, as when unlocking Silence I ain't in the right thread, `isVisible` is `false` so it calls another signature of `updateNotification`, where then as I'm testing with only one new message at a time, `sendSingleThreadNotification` is called.

Here's the notification is worked then trigerred with alarms as `notificationsRequested(flags)` is `true`.

Not sure if useful, but still digging.

**Comment by BastienLQ** [comment]
Alright, got it.

Yes, notification is displayed twice.
1. When a message is received but Silence is locked, showing "Encrypted message".
2. When Silence is unlocked, showing the decrypted message.

This is the intended behaviour of Silence: notification is rebuilt (and not updated; yes, updating the notification unstead of rebuilding it will fix the issue) with decrypted messages when Silence is unlocked. I thought both "Encrypted message" and decrypted messages were shown.

So now that I fully understand the issue, I'll see how to fix that. Sorry for this misunderstanding.

**Comment by canou** [comment]
Don't worry, I may not have explained it well either :-)
I thought it had something to do with the rebuild of the notification as the issue seems to have appeared since #478 (but forgot to mention it, and the screenshot doesn't show it as I don't display notifications content -_-" ).
So, the intended behavior is of course to update the notification with decrypted message content, as long as it's still in the notification tray, but it should not pop again, right ?
As I've begun to dig into it, I can still try to look at this issue and try to fix it if it can help you.

**Comment by BastienLQ** [comment]
@canou This issue is fixed, I'm cleaning my code before pushing it to GitHub. You can focus on another issue! ;-)

**Comment by canou** [comment]
Finally taking some time to answer. Great, I'll see what I can do on another issues then :-)
