### ISSUE TITLE
Ciphered duplicate message in conversations lists

### ISSUE THREAD

**Issue by ArchangeGabriel** [SilenceIM/Silence#498]
### Bug description
When a message is received multiple times (because of network errors or whatever), in the conversation view Silence marks it likewise (« Message doublon » in french, probably « Duplicate message » in english).

However, in the conversations list, where you get one line of the latest message of each correspondent, the duplicate message is displayed ciphered.

### How to reproduce
Wait for a duplicate message…

### Screenshots
Will try do add some later.

### Device info
- Device: OnePlusOne
- Android version: CM13
- Silence version and build ID: 0.14.6

**Comment by BastienLQ** [comment]
@ArchangeGabriel Are you able to build branch `fix-498` and test if issue is fixed?

**Comment by ArchangeGabriel** [comment]
Replying to your deleted message: yes I could, but it would have required backing up my messages, deleting all messages received after a duplicate occurrence, verify it’s fixed, and restoring the DB. Unless sending twice the same message does work as duplicate, in which case you can test it too, which seems to be what happened. ;)

**Comment by BastienLQ** [comment]
I edited source code to mark every message as duplicated, so I was able to get duplicated messages on my phone and fix that issue. ;)

**Comment by ArchangeGabriel** [comment]
Nice. :) Thanks for fixing it BTW, it was really a minor and not important issue, but to quote someone “Details make perfection and perfection is not a detail”. ;)
