### ISSUE TITLE
Silence doesn't support Geo URIs

### ISSUE THREAD

**Issue by rponline** [SilenceIM/Silence#501]
I recently have got a text with following content:
`geo:47.1234,8.1234?z=14`
(it was generated by osmand~)
I would like to open this Geo URI with an app which can handle Geo-Location Data (for example for directions, osmand~, ...)

There is also a RFC for Geo URIs:
https://tools.ietf.org/rfc/rfc5870.txt
https://en.wikipedia.org/wiki/Geo_URI_scheme

**Comment by ArchangeGabriel** [comment]
Good idea, will allow things like sharing one’s location to friends for meetup.
