### ISSUE TITLE
include new Emojis

### ISSUE THREAD

**Issue by Dionis0s** [SilenceIM/Silence#502]
how about including the new **Android Emojis** (Unicode 9) to be up 2 date?
In _iOS_ there are new since _v10.2_:
- [Unicode 9.0](http://emojipedia.org/unicode-9.0/)
- [Emoji 4.0](http://emojipedia.org/emoji-4.0/)

This would be very nice, especially in light of the fact that  [#390](https://github.com/SilenceIM/Silence/pull/390)! :)

thanks

**Comment by BastienLQ** [comment]
Fixed in c4bc34f91eeb106e7cf52a32831c4617e0c1effd.
