### ISSUE TITLE
Error when sending sms.

### ISSUE THREAD

**Issue by az35as6** [SilenceIM/Silence#504]
My phone cannot send sms (encrypted and unencrypted), but can receive them.
Silence was a system app when the bug occured,  I tried moving it to user app, but it didn't change anything.
The error stated by the app is simply "failed to send".
I don't think it's coming from the phone settings, considering the calls and sms reception are working.

**Comment by BastienLQ** [comment]
Do you have a dual-SIM phone? Silence supports multi-SIM devices on Android 6.1+ only (no generic API before). If so, put your SIM card in slot 1.

**Comment by az35as6** [comment]
Sorry, but the phone isn't a dual-SIM one. 
I tried running another sms client, and fell on the same bug.
Seem like the problem isn't comming from Silence, so the issue can be closed.

Thanks for your support anyway, have a great day.
