### ISSUE TITLE
Show message archived

### ISSUE THREAD

**Issue by atao** [SilenceIM/Silence#507]
Hi,
Is it possible to add button to show all archived messages?
Thanks

**Comment by BastienLQ** [comment]
Hi,
Scroll down, and you will see a button "Archived conversations". Tap on it and you will access to your archives conversations.
![archives](https://cloud.githubusercontent.com/assets/7220484/21547970/a34891ba-cde9-11e6-8aea-c2c3d0c92a0b.png)

**Comment by ArchangeGabriel** [comment]
Not very practical when you have hundreds of conversations… but for me at least this number shows that I don’t archive anything. ;p Maybe I should, but how does search work in this case for example?

Anyway, I think it would be easier to discover and access if we had a Material Design drawer menu on the left with this item in it. ;)

**Comment by atao** [comment]
Yes, @ArchangeGabriel you have right! Is it possible to add button on the top?

**Comment by BastienLQ** [comment]
We will add a menu entry.
