### ISSUE TITLE
Some flags are missing

### ISSUE THREAD

**Issue by johanw666** [SilenceIM/Silence#510]
### Bug description
In the newly created flag emojis, I'm missing some countries, for example the US and British flags. There are also less flags than in Signal, who has 257 flags (the US flag appears to be double in Signal).

I tested with 2 phones: on 1 I set Signal as default SMS app, on 2 Silence. On 1, I sent this message to 2:
![signal-sent-flags1](https://cloud.githubusercontent.com/assets/8427572/21573679/8dd87c2e-cee7-11e6-8ce5-aa5ccd9ed889.jpg)

On 2, I saw this comming in:
![silence-received-flags1](https://cloud.githubusercontent.com/assets/8427572/21573681/9031a306-cee7-11e6-95fb-4dc8d1b94ad0.jpg)

Both devices ran Android 4.4.4.

This is clearly not what is intended.

**Comment by BastienLQ** [comment]
Which Silence version do you have? v0.14.8 will bring refactored emoji support.

**Comment by johanw666** [comment]
Sorry, Silence 0.14.8 (self-built version as it's not yet in FDroid) and Signal 3.25.4 (released today).

**Comment by BastienLQ** [comment]
@johanw666 Can you confirm that #512 fixes this issue?

**Comment by johanw666** [comment]
Yes, this fixes it. I didn't even have to resend the message to test, the original which I kept is now displayed correct.
