### ISSUE TITLE
Please allow using the system emoji font

### ISSUE THREAD

**Issue by marmistrz** [SilenceIM/Silence#513]
Silence uses its own emoji font. Please allow using the system font.

I really hate the Android emojis, they're illegible to me, so I used the super cow powers to replace them with EmojiOne. Silence still uses the Android emojis, though.

**Comment by ArchangeGabriel** [comment]
Also, apparently Emojis are embedded in the app, which size increased a lot recently due to all those Emojis changes. Not sure whether this is really a good idea to embed them. Maybe that is related to “older devices”?

**Comment by BastienLQ** [comment]
We're not going to do that. Built-in emojis are designed to offer an identical experience to users.

**Comment by marmistrz** [comment]
The experience will be identical iff the user is running vanilla Android. Users who have changed their emoji font or are using a heavily modified ROM will get an inconsistent experience, because all their other apps use non-standard emojis.

And if the experience were to be exactly the same, what's the point of embedding emojis?

Why not give users the choice?
