### ISSUE TITLE
Can't send/receive SMSes on Blackberry OS

### ISSUE THREAD

**Issue by mj-harvey** [SilenceIM/Silence#522]
Hi,

I have Silence installed on a Blackberry Passport with OS version 10.3.2.2836. I have Silence 0.14.8 build 9c73379  installed from F-Droid and running using the OS's Android runtime.
Silence runs but is unable to send or receive SMSes. Sending gives the error "Failed to send"

Debug gist at https://gist.github.com/139c2f7476c6cfa3b4d8bd8a7efbab68

Probably the Blackberry android runtime simply doesn't give access to SMS functins, but can you confirm this for sure?

Ta,

Matt

### How to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug.

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Device info
- Device:
- Android version:
- Silence version and build ID:

**Comment by BastienLQ** [comment]
Looks like Blackberry doesn't offer APIs for GSM. Same as Sailfish users: adding support to these OSes will limit Silence's functionalities and won't offer a proper user experience.
