### ISSUE TITLE
MMS/group texts notifying twice

### ISSUE THREAD

**Issue by ineedanaccount** [SilenceIM/Silence#524]
Whenever I get a group text, I first get a notification that the message is currently downloading. Then when it downloads, it moves the text to the appropriate group and notifies me again. This means I get 2 notifications per group text. If I get 3 group texts, that means I'll get 6 notifications and so on.
What if for MMS messages there was an option to only notify if the message download was successful or not. I don't need a notification that a text is downloading if it will notify me anyway when it finishes, but I can understand someone may want that.
I've tried muting group texts as a workaround, but the problem is that I still get notifications from the users who send the texts. (Which might be another issue seeing as the group is technically not muted if I still get notified for every text being sent to that group.)

**Comment by sorenstoutner** [comment]
Thanks for fixing this.
