### ISSUE TITLE
Having trouble to send SMS via SIM2

### ISSUE THREAD

**Issue by thenanobel** [SilenceIM/Silence#527]
I use a dual SIM Android device. The default SMS app of Android let me select a SIM, before sending a SMS. But, Silence doesn't ask me anything about my preference. For sending a SMS via SIM2 using Silence, I have to go to "Settings > SIM Management > Messasing" and select the "SIM2", instead of "Always ask".

**Comment by BastienLQ** [comment]
Long-pressing on the send button will display every available SIM card.
But Silence should ask the user if no default SIM card is selected.

**Comment by thenanobel** [comment]
Long pressing the send button of a **secure conversation** is showing me two options "Secure SMS" and "Unsecure SMS". And nothing happens for a **unsecure conversation**.

**Comment by BastienLQ** [comment]
Which Android do you use?

**Comment by thenanobel** [comment]
Android 4.4.2 (KitKat).

**Comment by BastienLQ** [comment]
Android <5.1 does not offer an API for managing dual SIM devices and each manufacturer implemented its own way to manage it. Thus, Silence does not support dual-SIM before Android 5.1 and that is why you don't see SIM in slot 2.

**Comment by thenanobel** [comment]
Oh I see. However, thanks. 😊
