### ISSUE TITLE
Privacy policy

### ISSUE THREAD

**Issue by BLeQuerrec** [SilenceIM/Silence#528]
Because of `INTERNET` and `READ_CONTACTS` permissions (for MMS download and contact reading), **Google asks us to provide a privacy policy by March 15, 2017**.

We should write a small `PRIVACY.md` to explain why those permissions are required and that user's data is stored on the device only. Then add the link on the Play Store page.

**Comment by pR0Ps** [comment]
How "legal" does this have to be? Would the following be enough?

Silence does not collect or transmit any personal information. We require the following permissions:
 - INTERNET: This permission is required so the app can download MMS content from service providers. It it not used for any other purpose.
 - READ_CONTACTS: This permission is required to the app can suggest contacts to you as you type, as well as display contact information next to messages. This data is never transmitted off the device.
 - READ_PHONE_STATE: This permission is required to get the current phone number. This is used for some dual-sim functionality and to make sure you don't start a secure conversation with yourself. This information is never transmitted off the device.

Could go into detail about the others too

**Comment by BLeQuerrec** [comment]
Full mail:


> Hello Google Play Developer,
> 
> Our records show that your app, Silence, with package name org.smssecure.smssecure, currently violates our [User Data](https://play.google.com/about/privacy-security/personal-sensitive/) policy regarding Personal and Sensitive Information.
> 
> **Policy issue**: Google Play requires developers to provide a valid privacy policy when the app requests or handles sensitive user or device information. Your app requests sensitive permissions (e.g. camera, microphone, accounts, contacts, or phone) or user data, but does not include a valid privacy policy.
> 
> **Action required**: Include a link to a valid privacy policy on your app's Store Listing page and within your app. You can find more information in our [help center](https://support.google.com/googleplay/android-developer/answer/113469#privacy).
> 
> Alternatively, you may opt-out of this requirement by removing any requests for sensitive permissions or user data.
> 
> If you have additional apps in your catalog, please make sure they are compliant with our [Prominent Disclosure](https://play.google.com/about/privacy-security/personal-sensitive/) requirements.
> 
> Please resolve this issue by **March 15, 2017**, or administrative action will be taken to limit the visibility of your app, up to and including removal from the Play Store. Thanks for helping us provide a clear and transparent experience for Google Play users.
> 
> Regards,
> 
> The Google Play Team

There is no particular requirements and in my opinion what you wrote is enough. But it can be the occasion to explain more permissions.

**Comment by p4nci** [comment]
> But it can be the occasion to explain more permissions.

suggestion: add a new FAQ menu at https://silence.im similar to [Signal's What are all these permissions?](https://support.whispersystems.org/hc/en-us/articles/212535858-What-are-all-these-permissions) and explain all permissions

**Comment by johanw666** [comment]
@pR0Ps : "This permission is required so the app can download MMS content from service providers."

Is this technically complete? Is internet not also used to send MMS content?

**Comment by p4nci** [comment]
@johanw666 you're right
from Signal's "What are all these permissions?":
"For example, MMS sent over T-Mobile needs the cellular network and Wi-Fi turned off to succeed ..."
however, I don't now if this is true for Silence 😕

**Comment by BLeQuerrec** [comment]
This 2 specific permissions require a privacy policy:
* android.permission.READ_PHONE_STATE
* android.permission.READ_CONTACTS

**Comment by pR0Ps** [comment]
As the March 16th deadline is coming up, maybe we could drop the post I drafted up (feel free to improve it in any way) into the SilenceIM/silence.im repo somewhere and start serving it before the deadline, then open an issue over there in order the flesh it out some more (if required).

**Comment by BLeQuerrec** [comment]
@pR0Ps I'm working on it.
