### ISSUE TITLE
SMS away mode

### ISSUE THREAD

**Issue by davidhedlund** [SilenceIM/Silence#533]
It would be useful to offer "Away mode" that when activated automatically replies to incoming SMSes with a defined SMS message like "Sleeping".

**Comment by davidhedlund** [comment]
[mylabel:important](https://github.com/search?utf8=%E2%9C%93&q=commenter%3Adavidhedlund+%22mylabel%3Aimportant%22+in%3Acomments&type=Issues&ref=searchresults)

**Comment by BLeQuerrec** [comment]
This is not for what SMS messages are designed. This would be used in instant messaging status but SMS messages aren't designed to manage status.

**Comment by davidhedlund** [comment]
@BLeQuerrec There are other software that do the job. Please have a look on Google [sms auto reply](https://encrypted.google.com/search?hl=en&q=sms%20away%20message%20android#hl=en&q=sms+auto+reply).

**Comment by davidhedlund** [comment]
@BLeQuerrec However, there are no such solution on f-droid.org.
