### ISSUE TITLE
Document the use of Noto Emoji Project for emojis

### ISSUE THREAD

**Issue by davidhedlund** [SilenceIM/Silence#534]
Silence uses _Noto Emoji Project_ for its emojis. However this has not been documented in the [main page](https://github.com/SilenceIM/Silence) of the project.

Can you please add it?

**Comment by BLeQuerrec** [comment]
Silence uses AOSP emojis. AOSP emojis are partially based on Noto emojis. Thus, Silence does not directly use Noto emojis.

**Comment by davidhedlund** [comment]
@BLeQuerrec Thank you for the info. Can you document that AOSP emojis are used by Silence then?

**Comment by BLeQuerrec** [comment]
https://github.com/SilenceIM/Silence/blob/master/scripts/emoji-extractor/README.md

**Comment by davidhedlund** [comment]
@BLeQuerrec Thank you.
