### ISSUE TITLE
Archive des messages

### ISSUE THREAD

**Issue by reno-a** [SilenceIM/Silence#540]
Il ne s'agit pas d'un bug (?), mais comment accéder aux messages archivés ?
Sans doute que la solution existe, cependant elle paraît peu évidente.
Merci pour la solution.

**Comment by reno-a** [comment]
Je viens de trouver. C'est indiqué en toute fin du fil des messages envoyés.
Cette présentation pose un évident problème de convivialité. Il semblerait plus simple de pouvoir y accéder au travers des options, et même de pouvoir désactiver l'archivage si l'on en a pas besoin (cela peut éviter des erreurs de manipulation).

**Comment by reno-a** [comment]
Je viens de trouver. C'est indiqué en toute fin du fil des messages envoyés.
Cette présentation pose un évident problème de convivialité. Il semblerait plus simple de pouvoir y accéder au travers des options, et même de pouvoir désactiver l'archivage si l'on en a pas besoin (cela peut éviter des erreurs de manipulation).

**Comment by BLeQuerrec** [comment]
Hi,

Please use English to allow community to understand your issue and contribute. Archived conversations are available at the end of conversations' list. Upcoming release will also add a menu entry.

**Comment by reno-a** [comment]
Hello,
Thank-you for your answer and the future solution.
I try to use english, but (you see) it's not easy.
Have a nice day.
