### ISSUE TITLE
Feature: send single unencrypted SMS without breaking the keys

### ISSUE THREAD

**Issue by matya** [SilenceIM/Silence#541]
### Allow sending one time not encrypted SMS 
Having some tracking app on the phone, that can receive SMS commands from a given number of other phones is quite usual, like Eset anti virus or Cerberus. 

When both parties are using silence, and a handshake has been successfully done, the given app can not receive the SMS based commands without breaking the encryption completely, since that requires an unencrypted command being sent via plain text. 

Even this is possible and "easy", it requires the following KEX, which would not really be a necessity. 

This proposal is to allow single SMS being sent without discarding the established encryption, for remote control purposes, just like explained.

**Comment by AlfaOmega33** [comment]
+1

**Comment by pR0Ps** [comment]
You can send an unencrypted message in a secure session by long-tapping the send button and selecting the "insecure" option.

Sending an unencrypted message will not end the secure session.

**Comment by matya** [comment]
Thanks, this was the best outcome for the topic :)
