### ISSUE TITLE
[Feature-request] Hidden conversations

### ISSUE THREAD

**Issue by JoWilfrid** [SilenceIM/Silence#542]
I think it would be a geat improvment in terms of UX if we could have hidden conversations and group conversations!

## Example of use cases:

**1- The gift**

I'm living with my wife and it's valentine's day soon. I want to buy her a special gift as a surprise.
As we're very often together, I fear she sees one of the sms between I and her bestfriend to whom I asked for advices.
Plus I want to make her thinking I won't buy anything for her.

**2- The surprise party**

It's a friend's birthday soon and as we grown up, our friends aren't in the same city/country than us. I spend a lot of time with him and don't want to risk that he guess I'm talking to our old friends in order to organize the surprise party.

## Proposition:

I'd like to be able to hide entire discussions or to create new ones even if I have a non-hidden discussion with the same contact(s). Same for group discussions.
In my dreams, I could have whether a password per discussion or a password for all discussions.
For example by default, I set a password for all hidden discussions and I can override it for some of my contacts.
Since I've not gave my password to unlock hidden discussions, I don't want anybody which access my phone to be able do know if I have some or how many I have.
It would be great if, in addition, even if I have all hidden discussions unlocked, I don't see discussions with specific password.
Concerning notifications, I'm not sure about what would be best but I have some ideas:
* no notification
* with fake text, talking about something else and asking password (eg: we need your password to proceed some updates)
* fake error message (eg: error while processing messages indexation, please check the report)

As example, you can have a look at GoSMS Pro android app.

**Comment by BLeQuerrec** [comment]
Thanks for your proposal. We won't include hidden conversations as it would need a lot of modifications in DB. Silence can already be password-protected with internal DB encryption.
