### ISSUE TITLE
Notification generated even when conversation is open

### ISSUE THREAD

**Issue by yankee14** [SilenceIM/Silence#543]
### Bug description
I updated Silence from F-Droid repo today, 2/20/2017. Silence now unnecessarily generates status bar notifications when staring right at the conversation I receive messages from. I don't think status bar notifications should be necessary for currently-open conversations. Is this the new intended behaviour?

### How to reproduce
- Open a specific conversation in Silence
- Receive a message in that conversation
- Observe that a notification is generated

**Actual result:** Notifications are generated for currently-open conversations.
**Expected result:** No notification should be generated for a conversation I have actively open.

### Device info
- Device: Sprint LG G2 - LS980
- Android version: Cyanogenmod 12.1-20161016-NIGHTLY-ls980
- Silence version and build ID: 
Version 0.15.1
Build ID: 316b9fe

**Comment by BLeQuerrec** [comment]
I can't reproduce this bug but I saw it when using `unstable`... There is a missing step to reproduce it...

**Comment by sevan6** [comment]
Same issue. 
No specific action : in the conversation screen, when a message is received, the message is added to the conversation and at the same moment a notification (vibration, pop up and notification bar icon) is displayed. 

Tried only with a encrypted conversation.

**Comment by sevan6** [comment]
Moreover, received message is considered as unread (new widget count, highlight in conversations list) 

Debug log : https://gist.github.com/252c5b6a33b84e33c21d5b2bbaeec07b

**Comment by sevan6** [comment]
Still the same behaviour on 0.15.2
Looks it is not solved :(

**Comment by sevan6** [comment]
New log :
https://gist.github.com/79b8e6cce106b0900fda36da22106403

**Comment by BLeQuerrec** [comment]
0.15.2 doesn't include this commit. Next release will do.

**Comment by yankee14** [comment]
While troubleshooting #555 the problem persists in 0.16.0.
