### ISSUE TITLE
Allow translations for unstable branch

### ISSUE THREAD

**Issue by johanw666** [SilenceIM/Silence#545]
This is not really a bug but a development process issue: with Transifex I can only translate strings that are present in the master branch (unless I'm really missing something). When unstable is pushed to master and then immediately released the translators dont't have time to do any translation, so the translations are always (at least) 1 version behind in this schedule.

Possible solutions: would it be possible to send a message to all translators so they are informed a new version is about to be released and had new strings to translate? Or somehow making it possible to translate in the unstable branch?

**Comment by BLeQuerrec** [comment]
Transifex contains the unstable version of `strings.xml` and `distribution-strings.xml`. When new strings in `master` are pushed, a merge is done in `unstable` and version in Transifex is updated.

This is different than being notified when new strings to translate are available in Transifex. I will now send a message to translators when a new release is about to be published.
