### ISSUE TITLE
No "Download" button for MMS since 0.15.1

### ISSUE THREAD

**Issue by matlink** [SilenceIM/Silence#548]
### Bug description

Since 0.15.1, there is no more "Download" button when receiving an MMS. Only the message "multimedia message" appears.

When going in settings, option for automatically download MMS is missing. It was disabled for me (MMS were never downloaded automatically, I always pushed "Download").

### Screenshots

![silence](https://cloud.githubusercontent.com/assets/4450078/23233807/3f3d9160-f950-11e6-8535-b5ce254591eb.jpg)

### Device info
- Device: Hammerhead
- Android version: LineageOS 14.1
- Silence version and build ID: 0.15.1 316b9fe

**Comment by BLeQuerrec** [comment]
Thanks for your report. This issue will be fixed in v0.15.2.

**Comment by matlink** [comment]
Do you know when it will be pushed?

Le 22 février 2017 23:42:19 GMT+01:00, Bastien Le Querrec <notifications@github.com> a écrit :
>Thanks for your report. This issue will be fixed in v0.15.2.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/SilenceIM/Silence/issues/548#issuecomment-281829111

-- 
Matlink - sysadmin Matlink.fr

**Comment by BLeQuerrec** [comment]
Probably in less than 12 hours.
