### ISSUE TITLE
Play Store: Unknown error code during application installion: "-501"

### ISSUE THREAD

**Issue by Brains1** [SilenceIM/Silence#553]
'Error
Unknown error code during application installion: "-501"'

Trying to update to v0.15.2 in play store. It has left we without Silence completely now, not even the previous version.

Samsung Galaxy S4, lollipop 5.01, Rooted.

No problem installing or updating other apps in the play store.

Any idea what kind of areas cause this 501?

**Comment by BLeQuerrec** [comment]
It is not related to Silence but to the Play Store. Try to remove Play Store's data and retry.
