### ISSUE TITLE
Need to encryption of a message not sure how please help

### ISSUE THREAD

**Issue by amberbranson3** [SilenceIM/Silence#554]
### How to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug.

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Device info
- Device:
- Android version:
- Silence version and build ID:

**Comment by pR0Ps** [comment]
No information provided
