### ISSUE TITLE
Add changelog to Silence

### ISSUE THREAD

**Issue by davidhedlund** [SilenceIM/Silence#556]
https://github.com/SilenceIM/Silence/blob/master/CHANGELOG.md
> Added link to our Privacy policy in Settings

Can you please also add a link to the changelog itself?

**Comment by BLeQuerrec** [comment]
https://silence.im/privacy

**Comment by davidhedlund** [comment]
@BLeQuerrec Thanks but I mean add Settings -> Changelog. Can you please do that instead?

**Comment by davidhedlund** [comment]
[mylabel:open](https://github.com/search?utf8=%E2%9C%93&q=commenter%3Adavidhedlund+%22mylabel%3Aopen%22+in%3Acomments&type=Issues&ref=searchresults)
