### ISSUE TITLE
Encounter "Unfortunately, Silence has stopped." when opening any conversation

### ISSUE THREAD

**Issue by yankee14** [SilenceIM/Silence#557]
### Bug description
A friend just got a new phone, and Silence always throws a divide by zero exception when they click any conversation in the main window.

### How to reproduce
- Install any version of Silence from 0.15.2 - 0.15.5 or 0.16.0
- Open a conversation
- Crash

### Did not try
Any versions before 0.15.2

**Actual result:** Silence crashes when opening any conversation.
**Expected result:** Silence does not crash when opening any conversation.

### Device info
- Device: HTC 2PYB2 (acawhl_00651)
- Android version: 7.0 (821651.15, NRD90M release-keys)
- Silence version and build ID: 0.15.5, not sure on the build ID. Not my phone.

### Link to debug log
https://gist.github.com/anonymous/8a111a2d75323c8a43199a05a222e45f

Bug filed on behalf of the friend I mentioned in #555.

**Comment by BLeQuerrec** [comment]
Did you update Silence to v0.16.0 then downgraded to 0.15.x ?

**Comment by yankee14** [comment]
@BLeQuerrec Yes that has happened, but I don't think 0.16.0 was the first version they installed. I think they started with a stable build:

They said the very first version they installed "was the one on Google Play store" at the time. That confused me, since I thought Silence was not available on GP... Even the Silence website says it is not available there, and I cannot find it by searching. But they sent [this screenshot](https://i.imgur.com/J4eHfbg.jpg). Strange.

Anyhow, that image shows 0.15.4 is the default to be installed from GP, so the first version they installed was probably around 0.15.2. Whatever version it was, it crashed on them, so I guided them to try installing other versions by downloading apk directly from F-Droid website. At some point, that included 0.16.0, followed by having them try 0.15.5 yesterday.

**Comment by BLeQuerrec** [comment]
Play Store should not allow people to downgrade to 0.15 as database and keys management is completely different in 0.16... I'll update a new release with a bumped version code.

Anyway, this bug won't be fixed. You have to clean app's data.

**Comment by yankee14** [comment]
@BLeQuerrec Thank you for the advice. Do I have to instruct them to do anything special on their local filesystem, or is going to (Android OS) Settings -> Apps -> Silence -> CLEAR DATA enough to "clean app's data?"

Thanks

**Comment by BLeQuerrec** [comment]
Cleaning data from Android's settings should be fine.

**Comment by yankee14** [comment]
I asked them to clean Silence data, uninstall Silence, and install latest stable from F-Droid. They said it is still crashing. Here is the new debug: https://gist.github.com/9a8ce01590cd47a50157fc3f211bbcba

**Comment by yankee14** [comment]
@BLeQuerrec I asked them to clean Silence data, uninstall Silence, and install latest stable from F-Droid. They said it is still crashing. Here is the new debug: https://gist.github.com/9a8ce01590cd47a50157fc3f211bbcba
