### ISSUE TITLE
No notifications whatsoever

### ISSUE THREAD

**Issue by theatre-x** [SilenceIM/Silence#558]
### Bug description

Hello,

I can not get any notifications in Silence when a message arrives. No sound or visual notification ever when I get a text message. Notifications are on according to the settings in Silence and even the LED notification bulb is set to flash a color when I get a text. I have the sound on high as well.

### How to reproduce
Don't know. Using the app on my phone I would think.

**Actual result:** No notifications on my phone (i.e. the buggy behaviour)
**Expected result:** Hear a sound and/or see a notification icon.

### Device info
- Device: Samsung Galaxy J1
- Android version: 5.1.1
- Silence version and build ID: 0.15.5 | b198a25

### Link to debug log

https://gist.github.com/anonymous/f274ef99f53c2b363c10268b3d7656e5

**Comment by BLeQuerrec** [comment]
Are you sure that notifications aren't blocked from Settings (Android Settings --> Applications --> Silence --> Notifications)?
If they aren't, can you attach a debug log taken right after receiving a message?

**Comment by theatre-x** [comment]
You were 100% correct! I brought the issue to here because I remember seeing a bug getting patched that had to do with not getting notifications a few months back. Thank you so much. This is a long-standing frustration solved! Cheers! :)
