### ISSUE TITLE
Feature request: Support markdown

### ISSUE THREAD

**Issue by betsythefc** [SilenceIM/Silence#563]
Hello,

An app I once used (QKSMS) supports markdown and I would really love it if Silence supported this so we can send formatted messages to other Silence & QKSMS users.

Thanks!

**Comment by pR0Ps** [comment]
Markdown in an SMS application would be unexpected for the vast majority of users. I would think that most people outside of the developer world don't even know what it is. They would just complain that the markdown parser broke their URL or ¯\_(ツ)_/¯ or whatever.

**Comment by betsythefc** [comment]
Perhaps we could have it so markdown is in an "advanced settings" to enable on the receiving end. So my recieving texts would format as markdown if I enabled this feature? 

Or maybe markdown would only be able to be enabled on encrypted channels where others are using Silence as well?
