### ISSUE TITLE
MMS thumbnail broken

### ISSUE THREAD

**Issue by maxauvy** [SilenceIM/Silence#566]
### Bug description
Images sent via MMS are shown in the conversation thread. Normally, they're cropped to fit in a squared box. This "crop" step seems to be broken for a while, at least on my phone. The full image available by clicking on the thumbnail is OK though.

### How to reproduce
- tap on the paperclip to send a photo
- select a picture of your cat being cat
- (optionnally) write a text message to send with your cat pic
- tap the "Send" button
- enjoy your partially black thumbnail

**Actual result:** the cropped image used as a thumbnail is partially (or sometimes totally) black. 
**Expected result:** the sent image is cropped so the thumbnail fully fill the preview square in the conversation thread

### Screenshots
![screenshot_20170405-113342](https://cloud.githubusercontent.com/assets/2428307/24699685/246a0f1a-19f5-11e7-8861-9c74566cc505.png)

### Device info
- Device: LG G4 Intl (h815)
- Android version: 7.1.1 (LineageOS 14.1, 28/03 build)
- Silence version and build ID: 0.15.5 from F-Droid

I did the 0.15.6 update (and LOS 14.1 04/04 build update) this morning, but I didn't send any MMS since then.

### Link to debug log
Debug log saved yesterday right after sending the MMS in the screenshots section.
https://paste.open-freax.fr/?db2ddb789a591437#e6RaEGfh2LEMbFwNW0PjqY50hhTwYgqljRv6vYqe+FM=

**Comment by canou** [comment]
I can confirm this behavior too, Moto G 4G (peregrine), Lineage OS 14.1 30/03 nightly build.
Still happening on 0.15.6, but I can't remember since when it began to occur :-(

**Comment by maxauvy** [comment]
It did happen yesterday evening, so the bug persists with last Silence version.
Log: https://gist.github.com/anonymous/496f9910cb62d674fe63c1e489181648

**Comment by maxauvy** [comment]
Anything new on this ? Still happen with Silence 0.15.7 from F-Droid, LineageOS 14.1 (25/05 build). Thanks :-)

**Comment by MT-JAPP** [comment]
I've got the same issue. Instead of sending the pictures via MMS, I upload them to a website and then I send the URL via SMS. It's little bit more complicated, but it works!
Otherwise, this app is **awesome**, thanks :)

**Comment by owintwist** [comment]
Same issue her, both on Moto G LTE (Peregrine) with LineageOS and Galaxy  J7 2017 duos (sm-j730f/ds) with Stock Rom.
