### ISSUE TITLE
Space after message on iOS

### ISSUE THREAD

**Issue by LambdaUser** [SilenceIM/Silence#568]
### Bug description
When I send message from Silence with my phone, people using iOS receive the message with extra space at the end of the message, which enlarges the speech bubble.

### Device info
- Device: Fairphone 2
- Android version: 5.1
- Silence version and build ID: version 0.15.5

**Comment by pR0Ps** [comment]
This is by design. In certain cases Silence tags unencrypted messages with some whitespace at the end. This is so it can recognize messages sent by Silence and prompt the user to start an encrypted session.
