### ISSUE TITLE
Feature Request: Read & send of non-encrypted SMS by other applications

### ISSUE THREAD

**Issue by noc-jfcbs** [SilenceIM/Silence#574]
### Description
Personally I’m still a heavy user of SMS instead of messengers. By Silence, I send and receive both, encrypted as well as open messages e.g. from/to contacts that aren’t using Silence (but I advertise its use). With my former default SMS client, I preferred to write my text messages on my notebook. Notebook and cellular phone connect and synchronise via the tool “My Phone Explorer (MPE)”. Since my migration to Silence, MPE does not recognise text messages anymore that were sent or received by Silence.

I assume this is a feature intentionally built into Silence due to the encryption and not related to the MPE client.

If I’m correct with this assumption please allow me to request that at least the not encrypted messages can be read by other applications and that transmission of not encrypted messages via Silence can be initiated by other applications.
I fully concur that this does not apply to encrypted message traffic, but for open traffic it might become a selectable option in the Silence settings.

### How to reproduce
Not applicable

### Device info
- Device: Samsung Galaxy S3 LTE (GT-i9305)
- Android version: Resurrection Remix -N-v5.8.3
- Silence version and build ID: 0.16.3-unstable 47bea30

### Link to debug log
Not applicable

**Comment by johanw666** [comment]
It probably reads the system sms database, and Silence does not use it but stores sms and mms in its own, encrypted storage.

**Comment by pR0Ps** [comment]
Yes, Silence stores the messages in its own encrypted database. As a result, no other apps can access them. Something along the lines of #145 would solve this problem.

**Comment by noc-jfcbs** [comment]
Thanks, I appreciate the information and provide my comment at [#145](https://github.com/SilenceIM/Silence/issues/145).
