### ISSUE TITLE
Feature request: with dual-SIM phone, allow linking a SIM to a contact list

### ISSUE THREAD

**Issue by djibux** [SilenceIM/Silence#581]
On dual-SIM phones, I believe there should be a way to link a SIM card to a contact list.

I have two SIM cards, one for personal conversations, and the other one for professional ones.  My contacts are separate contact lists (CardDav for personal, ActiveSync for professional).  I believe there should be a way to set up Silence so that messages are sent with the proper SIM card automatically.

For contacts that are not in my contact list, the behavior described in #497 is what I expect (replying with the SIM that received the message).

**Comment by pR0Ps** [comment]
This is a lot of complication for a very tiny subset of users, sorry.
