### ISSUE TITLE
[HowTo request] How to put back SMS/MMS in place (Message app)?

### ISSUE THREAD

**Issue by wikijm** [SilenceIM/Silence#584]
### Bug description
HowTo request

### How to reproduce
N/A

**Expected result:** How can I save SMS/MMS from Silence to put back in place on Message app (Android 6.0.1 on SAMSUNG S5)?

**Comment by pR0Ps** [comment]
If you go to the export page, you can use the export plaintext backup option. This will drop a `SilencePlaintextBackup.xml` file on the SD card. This file is compatible with the [SMS Backup & Restore app](https://play.google.com/store/apps/details?id=com.riteshsahu.SMSBackupRestore).

Using that app, you should be able to import messages from the saved file into your system SMS database.

**Comment by wikijm** [comment]
Thanks a lot for your help 😍
