### ISSUE TITLE
Can chose default system emojis or personnal emojis

### ISSUE THREAD

**Issue by Dryusdan** [SilenceIM/Silence#587]
Hello :)   
It's not a bug report but a suggestion (I'm not a java developper :x )  

### Feature Request: 
Actually, some friends would like to migrate to silence but they would like keep their emojis.  
Is it possible to choose if we want to use our own emojis or app emojis (or just don't convert it)

Thanks :)

**Comment by pR0Ps** [comment]
Personally, I would like to just not touch emojis at all and leave that up to the OS and keyboard to work out. It would greatly simplify the input box code, save space in the app from not including all the emojis, and remove the need to maintain the tooling around keeping them updated.

However, the reason it's done the way it's currently being done is that there are issues with some popular flavors of Android not doing things properly and people being unable to use emojis at all unless they're included in the app. This sounds crazy to me even as I type it, so someone please correct me if I'm wrong.

Related to #513

**Comment by Dryusdan** [comment]
The system emojis is not display in application (all, not just silence) when is tip on keyboard ? App have to translate unicode to emojis ? o.O   

Personnaly also, lot of people like the UI of app, the feature and the privacy protection against some app (Facebook for exemple) but they dislike Android emojis... So they can't migrate to silence. :/  

Other question, why not use emojiones emojis ? Or purpose both ? :)

**Comment by BLeQuerrec** [comment]
Fixed.
