### ISSUE TITLE
Export Automatique [Suggestion]

### ISSUE THREAD

**Issue by qwertygc** [SilenceIM/Silence#589]
🇫🇷

Bonjour,

Une suggestion : exporter régulièrement et automatiquement la basé de donnée (celle en version chiffré). pourquoi ? Pour les pas doué comme moi qui désinstalle sans faire exprès l'application, et qui perde tout. Avec une sauvegarde, je n'aurais pas eu de problème.

🇬🇧

Automatical backup of database (crypted).

**Comment by pR0Ps** [comment]
Dupe of #412
