### ISSUE TITLE
Silence resizing images results in very low quality

### ISSUE THREAD

**Issue by jingofett** [SilenceIM/Silence#590]
### Bug description
When I send a screenshot that includes text, the sent image is horribly degraded and illegible. 

### How to reproduce
Send an image with text on Silence

### Screenshots
https://share.riseup.net/#JQNckmh9P8vzI0HqJ5-n2g - Source screenshot
https://share.riseup.net/#I-S5sx323WW46pHjSlDnDw - What Silence sent

### Device info
- Device: LG G3
- Android version: LineageOS 14.1
- Silence version: 0.16.3

### Link to debug log
https://gist.github.com/anonymous/50787b33ccca92924f6a2f320c036b3c

**Comment by pR0Ps** [comment]
Unfortunately, IIRC, this is the best we can do while using MMS. Different carriers have different limits on image sizes. If we don't pre-compress the image down before sending it, the carrier will do it instead. You can imagine how well that works when you're sending an encrypted image (spoiler: not at all).

**Comment by Conan1989** [comment]
Could image quality be controlled with an end user configurable setting?

**Comment by ArchangeGabriel** [comment]
The right solution is the XMPP feature. ;)

**Comment by spanktastic2120** [comment]
Can the in-app resizing at least be disabled for unencrypted chats? Or for encrypted chats sent via several messages which are stitched together on the recipient's device? 

Other messengers do not compress screenshots into oblivion like Silence does. I've been a user for a few months and this is a pretty frustrating anti-feature.

**Comment by bishtawi** [comment]
@pR0Ps Any chance we can revisit this issue for unencrypted chats?
