### ISSUE TITLE
delete duplicated messages

### ISSUE THREAD

**Issue by PhilLAL** [SilenceIM/Silence#591]
Hi there, 
I got every message duplicated. I do not remember having importing twice my messages from default sms app, but possibility exists.
Whatever, I would like to know if there is a way to delete all duplicated message?
Thank you

**Comment by johanw666** [comment]
At the moment only manually.

**Comment by pR0Ps** [comment]
This is correct, you will have to long-press to enter batch mode and tag each of the duplicate messages.

**Comment by PhilLAL** [comment]
I am not sure I got it correctly, one need to manually select each duplicated message to delete it.
Is so it will be very time-consuming for a 17Mb database, isn't it?

**Comment by johanw666** [comment]
Probably. However, if these messages are only those who you read from the system sms database you can also delete all messages and reimport them. If they are not all in the system sms database I'm affraid you're in for some tedious work.
