### ISSUE TITLE
Encrypted phone calls

### ISSUE THREAD

**Issue by rugk** [SilenceIM/Silence#606]
I like Silence, because you can use it as a fallback and at least encrypt some SMS.

Now, could you maybe even offer the same fallback for phone calls? I saw once that apps can get the permission to make phone calls, so if you so might you be – theoretically – able to encrypt phone calls in the "same way" as SMS…

**Comment by johanw666** [comment]
Interesting idea, but a quick search on the internet learned that this seems not possible. Apps who offer such functionality do this by using sip calls via a server, in which case you could as well use Signal.

**Comment by rugk** [comment]
Mhh, but searching for "alternative dialers" brings up [some apps](https://alternativeto.net/software/dialer-one/), so it may be that they could do phone calls.

And when one cannot get around that SIP thing, why not use an 127.0.0.1 SIP server, which is run by Silence, which then encrypts and forwards the thing into the usual phone network?
AFAIK you can setup an SIP account in the official dialer app, too, so that could make the integration quite seamless.
Although I would be fine with a simple in-app solution. There the big question is just: Can the app make phone calls by itself? (without calling the installed dialer?)

**Comment by johanw666** [comment]
They either use SIP (which is an protocol over the internet, so in that case why not use Signal for encrypted calls) or are a shell around the normal dialer and can not change the data sent through the channel (so no encryption possible).

**Comment by rugk** [comment]
Mhh, that sounds bad. So I am closing that issue.

**Comment by ArchangeGabriel** [comment]
You cannot encrypt GSM phone call AFAIK. Maybe things are a bit different with VoLTE, but I don’t think so. Else, you would likely be able to abuse the feature to send arbitrary amount of data using the “voice” channel instead of the “data” one.

Indeed, your only chances are over the Internet, in which case I recommend using ring.cx (note that F-Droid version is currently outdated and thus does not work).
