### ISSUE TITLE
Silence not using system emojis ( very noticeable in Android 8.0 Oreo)

### ISSUE THREAD

**Issue by nine7nine** [SilenceIM/Silence#607]
Hi, Silence should be using the system emojis, but does not appear to be.

After upgrading to Android 8.0 Oreo, I noticed that Silence is using older emojis and there doesn't seem to be a way to change that. Most (if not all) other messenger apps seem to have no problem using the proper system emojis, included in Oreo. It would be nice if this issue could be looked into, as it makes messaging with Silence very inconsistent and imho it makes more sense for a messaging app to pick up emojis from the system.

Thanks.

**Comment by ArchangeGabriel** [comment]
See mostly https://github.com/SilenceIM/Silence/issues/513. There is some sort of follow-up in https://github.com/SilenceIM/Silence/issues/587.

**Comment by nine7nine** [comment]
Thanks, I read through those tickets. It would seem I'm not the only one who doesn't like the embedding of emojis, but if I read that correctly; that's not going to change anytime soon?

For my own use, I have already fixed Silence locally and imported Oreo's emojis and rebuilt the app... this would have been a deal breaker for me; If i couldn't build silence with Oreo Emojis... I would have stopped using it, purely because of the lack of integration / consistency with the rest of the system.

If emoji's are going to continue to be embedded, maybe Silence should consider upgrading to Oreo's Emoji set??? Reason: they are far more consistent with iOS, samsung Emoji sets... I think google is retiring the android blob emojis for that reason, in part.

**Comment by ArchangeGabriel** [comment]
Upgrading to Oreo’s Emojis could be a thing, yes. Anyway there hasn’t been any activity from @BLeQuerrec during the last months except for publishing a canary… I’ll try to reach him to see whether he intends to resume dev any time soon and his opinion on this matter. ;)

**Comment by pR0Ps** [comment]
Please use #587 for further comments
