### ISSUE TITLE
Add Gboard Incognito mode to Silence

### ISSUE THREAD

**Issue by kxzaon** [SilenceIM/Silence#614]
Firefox Focus just add this mode in their V2, please consider looking to implement this ;

https://developer.android.com/reference/android/view/inputmethod/EditorInfo.html#IME_FLAG_NO_PERSONALIZED_LEARNING

https://developer.android.com/reference/android/support/v13/view/inputmethod/EditorInfoCompat.html#IME_FLAG_NO_PERSONALIZED_LEARNING

**Comment by johanw666** [comment]
That is already done in Signal (https://github.com/WhisperSystems/Signal-Android/commit/ba849bce2c90287e820a3008e9dc9a1b14de19fc) so it should become available in Silence too when the applicable changes are merged.
