### ISSUE TITLE
Different emojis between app, notifications and keyboard

### ISSUE THREAD

**Issue by NicolasMassart** [SilenceIM/Silence#617]
### Bug description
Latest update of Silence from Android PlayStore introduced a new keyboard and new emojis.

As they may be more consistent across other devices (ios ?) they are absolutely ugly compared to Google default ones on Android (IMO and also see my wife reaction in screenshots).

But the most important problem is that they are not looking like the ones shown in the new message notification on Android or on the default keyboard while typing. So you see a nice message notification with cool emojis and then when you enter the app, the message is not the same and has ugly ones. Or you type on a nice emoji on your keyboard and an ugly one appears in your compose text field...
We really feel like we were defaced or our message was altered. Today communication uses emojis a lot. So a cute one that indicates we smile is now different and can lead to misunderstanding. Also older messages are affected and then meaning of past discussions... huge impact on relationships... I'm not trying to maximize the impact, this is just how we (my wife and I) felt this change.

### How to reproduce
**For notifications bug**:
- compose a message and insert emojis using Silence Emoji list (see screenshot 1)
- send it to a fiend that also use silence for Android
- wait for a notification to appear and notice the difference between the notification emojis and the in app emojis. (see screenshot 2)

**Actual result:** 
- Shows nice emojis in notifications and ugly ones in the app (see screenshot 3)

**For keyboard native emojis bug**:
- compose a message and insert emojis using default Google keyboard Emoji list (the 4th screenshot)
- notice that inserted emojis are not the one you touched on.

**Actual result:** 
- Inserts the ugly emoji in the compose text field even if nice emoji was selected

**Expected result:** Nice emojis everywhere

### Screenshots
screenshot1 : The keyboard with new emojis.

_Fyi, the message is "[Ugly Crying emoji] it's really terrible. I think I will never write SMS ever again". My wife is really shocked by these new emojis..._
![screenshot1](https://user-images.githubusercontent.com/4677568/31386600-a27898b6-adc7-11e7-83bd-fffbe0dcba5c.png)
screenshot2: the emoji as it appear in the notification using the default Android nice look (not obvious on this emoji, I know, but enough to notice that it's not the same as on the next screenshot)
![screenshot2](https://user-images.githubusercontent.com/4677568/31386601-a29470f4-adc7-11e7-86f4-da203726ce57.png)
screenshot3 : the emoji as it appear on the app
![screenshot3](https://user-images.githubusercontent.com/4677568/31386602-a2aaaeaa-adc7-11e7-9c9a-e00a7b464609.png)
screenshot4: the emojis look different on the keyboard and in the text field while we type !
![screenshot4](https://user-images.githubusercontent.com/4677568/31386603-a3ab43fa-adc7-11e7-92db-2f9952a4a685.png)

### Device info
- Device: Moto X Play and Moto G5
- Android version: Android 6.0.1
- Silence version: 0.15.8 from Google Play store updated on 2017 octobre 9th.

**Comment by johanw666** [comment]
There is no iOS version of Silence so that isn't there. The emojies were upgraded to the changed version that Android 8 uses, and because most people don't use Android 8 (yet) they might look different.

**Comment by NicolasMassart** [comment]
Do you mean upcomming Google Android O emojis will be the ugly ones ? Oh nooooooooooooo!
=> http://www.androidpolice.com/2017/05/18/change-org-petition-google-bring-back-old-cat-emoji-android-o/
