### ISSUE TITLE
add support for Librem 5

### ISSUE THREAD

**Issue by takiainen** [SilenceIM/Silence#619]
Consider adding support for the upcoming open source Librem 5 phone. Encrypted text messages would be perfect match for it.

https://puri.sm/shop/librem-5/

**Comment by johanw666** [comment]
That would require either a complete rewrite, or the porting of some Android runtume to PureOS which is Debian based according to their website. Both are major undertakings, which I think are way beyond the scope of this project unless there would be a serious inflow of developers.

**Comment by pR0Ps** [comment]
Exactly what @johanw666 said
