### ISSUE TITLE
Gradle Sync Error

### ISSUE THREAD

**Issue by xxrocks** [SilenceIM/Silence#625]
Hello ,  I'm pretty new to Android Coding 
  I used both android studio 2.3 and 3.0  but still getting this error 

> Error:Project : declares a dependency from configuration 'compile' to configuration 'default' which is not declared in the descriptor for project :org.w3c.dom.

what Should I do ?

**Comment by pR0Ps** [comment]
I remember getting this error when some of the subprojects were missing. Did you follow the instructions here (especially the `git clone --recursive` part)? https://github.com/SilenceIM/Silence/blob/master/BUILDING.md

**Comment by xxrocks** [comment]
I didn't saw that.  I just downloaded the project and tried to  open it with android studio ( new to android developing :) )  
After following instructions on "Building Silence "  Project   built  without problem 

 Thank You
