### ISSUE TITLE
Tasks screen suddenly closed

### ISSUE THREAD

**Issue by buckelieg** [SilenceIM/Silence#627]
### Bug description
Tasks screen is immideately closed after silence is closed.

### How to reproduce
1) Install silence app.
2) Open some app(s)
3) Open silence app.
4) Open tasks screen
5) Swipe to close silence window.

Actual result: Tasks screen is immideately closed.
Expected result: Tasks screen is still opened.

### Device info
- Device: Sony XPeria Z3 Dual
- Android version: LineageOS 14.1
- Silence version: Latest.

**Comment by BLeQuerrec** [comment]
This is an Android bug, out of the scope of Silence.
