### ISSUE TITLE
Share with options crashing after install

### ISSUE THREAD

**Issue by buckelieg** [SilenceIM/Silence#628]
### Bug description
share with menu is not shown correclty.

### How to reproduce
1) Install Silence app.
2) Open gallery.
3) Select a photo/media
4) Choose share with...

Actual result: recently shared contacts are displayed. No list of possible destinations is displayed.
Expected result: share with menu is fully available.

### Device info
- Device: Sony XPeria Z3 Dual
- Android version: LineageOS 14.1
- Silence version: Latest

**Comment by buckelieg** [comment]
I suppose that this issue is connected with this one: https://github.com/SilenceIM/Silence/issues/627 and vice versa.

**Comment by BLeQuerrec** [comment]
I don't really understand what you expect. If you _just_ installed Silence, there is no recent conversation: you can't expect Silence to display non-existent conversations. This is the expected result and Silence will not read conversations in other applications unless you ask to import SMS messages (and in that case, last conversations' list is based on imported conversations in Silence, not on conversations in the other applications).
