### ISSUE TITLE
Encrypted backup is broken

### ISSUE THREAD

**Issue by maxauvy** [SilenceIM/Silence#631]
### Bug description
The encrypted backup option seems to be broken, exporting data make the app crash.
I can't test restoring an encrypted backup, which may suffer from the same bug, as I can't export in the first place ;)

### How to reproduce
- Open Silence
- Go to the Import / Export menu
- Export an encrypted backup

**Actual result:** Silence crashes after creating only a few empty folder and files on the internal storage
**Expected result:** Silence exports its data on the phone's storage

### Device info
- Device: OnePlus 3T
- Android version: 7.1.2 (LineageOS 14.1 official build)
- Silence version: 0.16.4-unstable from F-Droid, and 0.16.5-unstable built from source

### Link to debug log
Here : https://paste.open-freax.fr/?e6ce0735bea762ab#ni1BEPePcoywJ12K+m8eg2B+XUfV0dY11pvCn4Z1vYk=

**Comment by maxauvy** [comment]
The logs after building the fix branch you mentionned on Mastodon:
https://paste.open-freax.fr/?91ed0840e54cd0d6#a7RDsjmrjoRLTa+f8KBLutucCGgUq8IQAKSiplwtXOs=

No crash during the exort, it ends with more complete SilenceExport folder, but as you said, it is maybe not really complete :wink:

**Comment by BLeQuerrec** [comment]
@maxauvy Can you try the updated `fix-631` branch with commit 8e9566f? This should fix the issue and your backup should be complete.

**Comment by BLeQuerrec** [comment]
Again, I need a debug log generated right after the export.

**Comment by maxauvy** [comment]
Here you are:
https://paste.open-freax.fr/?7277e6b1405a268e#dUGE4hVesArt+cESdDMu2ZbDvGDlxeIUvr2yqoHLhBA=
