### ISSUE TITLE
Register on weblate for easy translation

### ISSUE THREAD

**Issue by mobtechpd** [SilenceIM/Silence#643]
https://hosted.weblate.org/projects/

**Comment by licaon-kter** [comment]
I'd rather have them use Transifex or Crowdin.
Using all 3 of them, I find Weblate the most unhelpful one.

**Comment by ArchangeGabriel** [comment]
https://www.transifex.com/silence/silence/

**Comment by pR0Ps** [comment]
We're currently using Transifex and will keep using it for the foreseeable future.
