### ISSUE TITLE
Silence 0.15.11 not appearing on F-Droid

### ISSUE THREAD

**Issue by johanw666** [SilenceIM/Silence#648]
Silence 0.15.11 does not appear to be distributed on F-Droid, while 0.16.7-unstable that was released on the same day is already there since january 5. Considering the issues with the unstable versions people might not want to switch to them yet. Is this some issue with F-Droid or done deliberately?

**Comment by johanw666** [comment]
Sorry but what is a "missing log" case?

**Comment by licaon-kter** [comment]
See: https://gitlab.com/fdroid/fdroiddata/issues/1081

It means exactly that, no f-droid server build log for that version.

**Comment by licaon-kter** [comment]
It's a resource problem, not enough devs, can you help? No? Ok... quoting Moxie was useless then.

Making the app "build reproducible" might help too.

**Comment by ArchangeGabriel** [comment]
It was finally built today. :)

**Comment by licaon-kter** [comment]
@BLeQuerrec close this
