### ISSUE TITLE
[QUESTION] Bold letters

### ISSUE THREAD

**Issue by Woodzrul** [SilenceIM/Silence#649]
Admittedly I am a noob, but trying to learn. If I wanted the have the conversation profile pictures (first letter of forename) etc. in bold, what line of could would I need to amend to achieve this?

Please see attached example from the standard Contacts app that comes with LineageOS.

Thanks in advance. 

![img_20180114_092612](https://user-images.githubusercontent.com/23718359/34914587-4b379886-f90d-11e7-8e17-4547eaf05ab6.jpg)

**Comment by pR0Ps** [comment]
That would be handled in [TextDrawable.java](https://github.com/SilenceIM/TextDrawable/blob/master/library/src/main/java/com/amulyakhare/textdrawable/TextDrawable.java) in the [TextDrawable](https://github.com/SilenceIM/TextDrawable) library that Silence uses.

**Comment by Woodzrul** [comment]
@pR0Ps Sorry for the delayed response. I appreciate if you're busy, but would you be so kind to tell me if I am correct in thinking that line 175 needs amending? Changing 'false' to 'true'.

**Comment by pR0Ps** [comment]
You could, although I wouldn't recommend that. The proper way would be to use public methods on the `TextDrawable` object to configure it from within Silence. Here's a bit of a walkthrough:

Looking at [TextDrawable.java](https://github.com/SilenceIM/TextDrawable/blob/master/library/src/main/java/com/amulyakhare/textdrawable/TextDrawable.java), we can see a `Builder` class that is used to build a `TextDrawable` object (Sidenote: This is called the [builder pattern](https://en.wikipedia.org/wiki/Builder_pattern)). That `Builder` class has the method `bold()` that sets `this.isBold` to `true`.
```
public IConfigBuilder bold() {
            this.isBold = true;
            return this;
}
```

Now that we know how to build bolded `TextDrawable` objects (by called `.bold()` on their builders), we just need to find where Silence instantiates them.

By searching for "TextDrawable", we find that Silence generates the contact pictures in [GeneratedContactPhoto.java](https://github.com/SilenceIM/Silence/tree/master/src/org/smssecure/smssecure/contacts/avatars/GeneratedContactPhoto.java) using the following code:
```java
return TextDrawable.builder()
                   .beginConfig()
                   .width(targetSize)
                   .height(targetSize)
                   .textColor(inverted ? color : Color.WHITE)
                   .endConfig()
                   .buildRound(getCharacter(name), inverted ? Color.WHITE : color);
```

At this point it should be fairly obvious that we just need to insert a `.bold()` line somewhere in that chain to create a bolded version of it:
```diff
return TextDrawable.builder()
                   .beginConfig()
                   .width(targetSize)
                   .height(targetSize)
                   .textColor(inverted ? color : Color.WHITE)
+                  .bold()
                   .endConfig()
                   .buildRound(getCharacter(name), inverted ? Color.WHITE : color);
```

Now just rebuild the app and make sure it did what you expected.

**Comment by Woodzrul** [comment]
Really late in replying, but only had a chance to test the above recently. Really just want to say a massive thank you. You're the first developer who has actually taken time out of their busy schedule to reply with a detailed answer.

Please continue with this level of support. Its excellent! :-)
