### ISSUE TITLE
Please stop misinforming people

### ISSUE THREAD

**Issue by KOLANICH** [SilenceIM/Silence#666]
>Silence is an SMS/MMS application that allows you to protect your privacy while communicating with friends.
>Using Silence, you can send SMS messages and share media or attachments with complete privacy.

Since metadata is not protected Silence doesn't allow protecting privacy and doesn't enforce complete privacy. It only allows confedintiality and possibly (I have not dug into it or actually used, just saw it announce in f-droid) integrity of the messages.

**Comment by ArchangeGabriel** [comment]
I agree, both instance of “privacy” should be replaced by “confidentiality”, at least until there is XMPP support (if that is still planned). Even then, it should be said by something like “For enhance privacy, you can also use a data connection to send messages while protecting your privacy”.

**Comment by pR0Ps** [comment]
IMO The fact that it mentions SMS multiple times makes it clear that it's just an encryption layer over SMS messages with all the disadvantages that entails.

**Comment by KOLANICH** [comment]
It is clear for us, but not for ordinary people.

**Comment by p4nci** [comment]
@KOLANICH You confound privacy with anonymity. Definitely Silence `allows you to protect your privacy` but do NOT provide anonymity (yet?). On the Internet you can find many articles about privacy vs. anonymity.

**Comment by ArchangeGabriel** [comment]
@p4nci There is no real privacy without anonymity.

**Comment by gdt** [comment]
One should also be careful not to fall into the trap of assuming that anonymity against one particular attacker is what matters.   Signal appears to protect against phone companies observing the identity of your peers by replacing it with OWS being able to observe this.  Depending on a lot of things, that might be good.  But I know of nothing that has a beyond-criticism combination of security properties, usability for normals, and good energy/CPU behavior.  So perhaps

Silence is an SMS/MMS application that allows you to send messages while protecting the content from interception.   (It does not hide the identities of your correspondents from the cellular provider or those with access to that provider's logs.)

might be better.

**Comment by KOLANICH** [comment]
Could you explicitly document your threat model?

**Comment by BLeQuerrec** [comment]
We never claimed that metadata is masked with Silence. It's quite the opposite: I always warned about that, and it is the main reason I work on XMPP transport. Privacy doesn't mean masked metadata.

Your behavior is quite haughty, @KOLANICH. Please do not FUD or troll here.
