### ISSUE TITLE
Import/Send/Receive SMS content truncated to 2000 chars

### ISSUE THREAD

**Issue by williamdes** [SilenceIM/Silence#667]
### Bug description
Truncated sms content

### How to reproduce
- Send to someone (or yourself) this content : https://pastebin.com/raw/msiZcU3W
OR
- Use system app
- Send && Receive this content : https://pastebin.com/raw/msiZcU3W
- Go back to Silence
- Import system database

**Actual result:**
The preview of the message contains all the content (OK)
Silence cuts the content when sending/receiving the message.

**Expected result:** 
Like system app : do not truncate my content.

#### System app
![28870162_2075980406004000_2698510213861867520_o](https://user-images.githubusercontent.com/7784660/37217136-fd71a9ea-23bc-11e8-9412-f6e8f29b67d3.jpg)

### Imported system database result 
![28795493_2075981472670560_5128370150344491008_o](https://user-images.githubusercontent.com/7784660/37217133-fbbfc00a-23bc-11e8-8d26-3f268399ebe6.jpg)

### Device info
- Device: Meizu M5
- Android version: 6.0
- Silence version: 0.15.12 && 0.16.5-unstable

### Test data n°2
URL: https://pastebin.com/raw/b1BaDwdb

#### System app
![s80311-19512797](https://user-images.githubusercontent.com/7784660/37257197-1506f2ae-2566-11e8-8e1b-7747c4f2b795.jpg)

#### Signal after system database import
![s80311-19511420](https://user-images.githubusercontent.com/7784660/37257201-21a12e58-2566-11e8-9d06-229b6496a444.jpg)

### Test data n°3
URL: https://pastebin.com/raw/Zf2crTYS

**Comment by johanw666** [comment]
Apparently not all emotions are used in Silence. Those who are not used show as a white rectangle.

**Comment by williamdes** [comment]
That is not the actual problem.
Use test data n°2:
https://pastebin.com/raw/b1BaDwdb

**Comment by williamdes** [comment]
@BLeQuerrec ?

**Comment by williamdes** [comment]
Related to https://github.com/signalapp/Signal-Android/issues/5146

**Comment by williamdes** [comment]
See https://github.com/SilenceIM/Silence/issues/98#issuecomment-97618436

Issue solved when changing ```MAX_DISPLAY_LENGTH``` in [MessageRecord.java](https://github.com/SilenceIM/Silence/blob/572dacab8564f59b490d1c6a9a4388cc7d087056/src/org/smssecure/smssecure/database/model/MessageRecord.java#L47)
```java
public abstract class MessageRecord extends DisplayRecord {

  private static final int MAX_DISPLAY_LENGTH = 2000;
```

**Comment by williamdes** [comment]
@Blequerrec what do you think about this issue ?
Raise the limit or add an option to bypass the limit because we dont care about it (IMHO) ?
