### ISSUE TITLE
Copy of Silence on Google Play

### ISSUE THREAD

**Issue by Poussinou** [SilenceIM/Silence#677]
Hi,

I found [this app](https://play.google.com/store/apps/details?id=com.smsmms.privatemessage) on the Google Play Store. This guy just took your source code, added some ads in it and put it on the Store, without warning this is free software...

As you are the owner of the source code, feel free to open a request to google [here](https://support.google.com/legal/contact/lr_dmca?product=googleplay) to remove the copy from the Store, if it's your wish ;)

Don't forget to tell Google that:

* The app is licensed under GNU GPL license and this guy is violating it;
* He is falsely claiming he made the app;
* Provide some screenshots of your own app.

**Comment by ArchangeGabriel** [comment]
Woh, it’s way more obvious than app screenshot, they even left “Silence” in the description:
![silence](https://user-images.githubusercontent.com/490531/38454641-65d6f8c4-3a5a-11e8-8473-8807049fb653.png)

**Comment by ArchangeGabriel** [comment]
OK, apparently there might be way more. I was intrigued by the NewPipe like app they have (see on the right part of the screenshot), and I was right, it’s a NewPipe clone. But that’s only the tip of the iceberg, see https://github.com/TeamNewPipe/NewPipe/issues/539. I’m wondering if Silence is affected that much too.

**Comment by Poussinou** [comment]
If you find any other copies of Silence, please copy paste the links here ;)
There are tons of copies of open-source apps on Google Play... I try to report them when I find them.
( @ArchangeGabriel are you french? Otherwise, are you playing HOMM5?^^)

**Comment by ArchangeGabriel** [comment]
Yes I’m french, you can easily see that from my profile. And yes, I play(ed) HOMM5. ;)

**Comment by johanw666** [comment]
But because Silence itself is a fork of Signal they might have something to say about that too.

**Comment by Poussinou** [comment]
Should I open a new Issue on their side, and link them to this one?

**Comment by BLeQuerrec** [comment]
Thank you @Poussinou for this report! I have filled in the form you linked and the request has been received by Google. I'm keeping that issue opened until that app is removed.

**Comment by johanw666** [comment]
https://play.google.com/store/apps/details?id=com.smsmms.privatemessage gives a 404 now, just like their NewPipe clone (thanks for mentioning that app, I didn't know it but like it). Apparently Google has waken up and responded to the reports.

**Comment by Poussinou** [comment]
Great ! Do not hesitate to report it here if you find another copy, and provide the URL, so that I can track the fake developer :)
