### ISSUE TITLE
No badge on icone app

### ISSUE THREAD

**Issue by AqwelF** [SilenceIM/Silence#685]
### Bug description
when I receive  a new message :
I receive the notification on statut bar.
But I doesn't have a badge notification on icon apps.
When I go to notification config panel, silence doesn't appear on list.
Is that a bug ? An absent option ?

### Screenshots
![screenshot_20180518-145935](https://user-images.githubusercontent.com/39408552/40236335-c36eb550-5a9c-11e8-8bb9-c8a26555f95e.jpg)

### Device info
- Device: Huawei Honor 9
- Android version: STF-L09 8.0.0.362 (C432) OREO 8.0 Under EMUI 8 (stock rom)
- Silence version: 0.16.9

**Comment by johanw666** [comment]
There is a widget installed with Silence that can do that.

**Comment by AqwelF** [comment]
You right but you can't put the widget on the dock...

**Comment by BLeQuerrec** [comment]
It's not a stock Android feature and it relies on the launcher. This requires to manage every launcher that offers this feature (with different APIs for each). We decided to remove the badge on the icon in favor of a widget to get ride of an old and unmaintained library.
