### ISSUE TITLE
Fake text message

### ISSUE THREAD

**Issue by protoloo** [SilenceIM/Silence#695]
I would like to ask, if possible, to add the possibility of creating fake sms within the app. Something like this:
1) select date and time of message:
- xx:xx, dd/mm/yyyy
2) select the type of message you want to fake
- inbox, sent, draft, outbox, failed
3) write the message text
4) "sent"

**Comment by licaon-kter** [comment]
What does "fake" mean?

What are these "inbox, sent, draft, outbox, failed" ?

**Comment by protoloo** [comment]
You know that, to send a text message: first write it, then click on send and at the end the message just sent will be sent with the wording

"sent" if it has been sent,

"failed" if the mobile phone failed to send it,

etc ..

"fake" means that you can write the message and pretend to send it, without actually sending it and you will have a message identical to the real one in your mobile phone.

**Comment by pR0Ps** [comment]
This is out of scope, closing.

**Comment by ArchangeGabriel** [comment]
@protoloo If you want to do this, you should just write a XML backup file manually and restore it into Silence.

**Comment by NitroNils** [comment]
Brilliant! 

On June 15, 2018 9:33:55 AM GMT+02:00, notifications@github.com wrote: 
>@protoloo If you want to do this, you should just write a XML backup 
>file manually and restore it into Silence. 
> 
>-- 
>You are receiving this because you are subscribed to this thread. 
>Reply to this email directly or view it on GitHub: 
>https://github.com/SilenceIM/Silence/issues/695#issuecomment-397538720 

-- 
Sent from my p≡p for Android.
