### ISSUE TITLE
add geo uri

### ISSUE THREAD

**Issue by qwertygc** [SilenceIM/Silence#699]
Hello,

I have a little suggestion, it's the possibility to send a geo urihttps://en.m.wikipedia.org/wiki/Geo_URI_scheme

I use this function in WhatsApp or Conversations and it's very pratical (for example, in rendez-vous).

**Comment by whiver** [comment]
It would need to add the location permission to Silence and I don't think that's something we want for an app dedicated on privacy, especially for a little feature like that. BTW, you can still share your location via Silence using another app (like Google Maps). if you want to.

**Comment by qwertygc** [comment]
Ok think.
