### ISSUE TITLE
How to bypass automatic key exchange?

### ISSUE THREAD

**Issue by jwc866** [SilenceIM/Silence#718]
Hello:
I am seeing the known issue where one of my contacts cannot receive my key when I try to Start a Secure session with them.  Silence on their phone just sees my request but it is coming through as two SMS messages and I think Silence doesn't know what to do with it.  Is there a way to bypass this limitation of the carrier, and manually send them my key and install it to their Silence app on their phone?  I have been looking for a way to do this but so far haven't found out how.
Thank you.

**Comment by jwc866** [comment]
The other user ended up porting their phone from a CDMA network (Spring) to GSM (T-Mobile) and it works now.  Apparently CDMA networks have a text limitation that GSM does not.  Hope this helps others!

**Comment by johanw666** [comment]
I didn't realize CDMA was even supported by Silence but from what I read on several sites the size limit for sms on CDMA networks vary.
