### ISSUE TITLE
No suggested correction in android keyboard

### ISSUE THREAD

**Issue by meaz** [SilenceIM/Silence#720]
### Bug description
I'm on Lineageos 15.1 on a Galaxy S4 mini.
I use Silence 0.15.13 from fdroid.
When I'm writing a message on Silence, I don't have suggested corrected words that appear in the keyboard, as it does on any other app that I have installed. That is why I think it comes from Silence. 
I didn't have this issue when I was on Lineageos 14.1

**Comment by licaon-kter** [comment]
Did you toggle the incognito feature in Silence Settings?

**Comment by meaz** [comment]
You're everywhere licaon-kter!
Anyway, that was indeed the issue: the incognito feature was toggled.
However, it was by default, I didn't enable it myself.
Thanks a lot.

**Comment by ArchangeGabriel** [comment]
See #719.
