### ISSUE TITLE
Google Play?

### ISSUE THREAD

**Issue by TheOtterslider** [SilenceIM/Silence#727]
On the front page of the project, I follow this link:  https://play.google.com/store/apps/details?id=org.smssecure.smssecure to google play.  When signed into my google account, I get a page that says "We're sorry, the requested URL was not found on this server.".  However, if I use another browser not signed into my google account, I get a page showing the application I can install.  Ideas?

**Comment by TheOtterslider** [comment]
The google account is a US google account.  I'm physically present in the UK though.

I was using the browser on my computer.

**Comment by OffifialMITX** [comment]
@TheOtterslider Then it must be blocked where you are, since GPlay shows it just fine here in Germany. I recommend to switch to [F-Droid](https://f-droid.org/).

_Sent from my Moto E (4) Plus using [FastHub-Libre](https://github.com/thermatk/FastHub-Libre/)_

**Comment by pR0Ps** [comment]
@TheOtterslider See https://github.com/SilenceIM/Silence/issues/425#issuecomment-233124050
