### ISSUE TITLE
RIP Silence

### ISSUE THREAD

**Issue by UMBRAGITHUB** [SilenceIM/Silence#728]
I know it's Google killed Silence. Because they also kill everything I love, buy every independent apps I use, poison every opensource ROMs I use, DDOS and raid every cloud server or VPN service I use, spam and block every webmail severs I use, change and force new rules on every goverment's GSM or ISP of other countries, block or copy every independent social websites, delete every rare Youtube videos I've bookmarked, steal every words I've said in messaging apps, and then sell it as music on Youtube. Because I am the real star!

Here's important message for all developers: BE PREPARE. Because when I use your apps, or services, they will come to you shortly, with unlimited money, or force, or nonsense like targeting terrorist. Because I am a dangerous baby!

So be prepare guys, take the money but don't submit to their will. Keep create new clean apps. Thanks.

**Comment by licaon-kter** [comment]
Link to this information?
