### ISSUE TITLE
add a function

### ISSUE THREAD

**Issue by krominet** [SilenceIM/Silence#733]
Hello,

sometimes , i wish have a zoom function in my SILENCE app . Like my old sms app ...
Is it possible ?

I wish to all of readers an HAPPY NEW YEAR !

**Comment by licaon-kter** [comment]
Zoom of?

**Comment by krominet** [comment]
Sorry, i don't know if this is a bug of my phone or if silence need this function..
in my standard SMS/MMS app i can zoom the content of a message to identify the smileys (when i forgot my glasses) but not in SILENCE app.
tried on gt-i9195i under lineageos 14.1 , and alose with gt-i9300.
With by best Regards.
