### ISSUE TITLE
MMS are not exported to unencrypted backup

### ISSUE THREAD

**Issue by Mistress-Anna** [SilenceIM/Silence#739]
### Bug description
When using unencrypted backup export (in "SMS backup & restore" format), MMSes are ignored, unlike "SMS backup & restore" app, which makes this backup slightly useless, especially as there's no warning message telling the backup lost data in the process.

### How to reproduce
- select "export"
- select "unencrypted backup"

**Actual result:** XML file doesn't contain MMSes (and at the very minimum a warning)
**Expected result:** XML file should contain MMSes

### Device info
- Silence version: 0.16.9

**Comment by pR0Ps** [comment]
See #597 , #140

**Comment by ArchangeGabriel** [comment]
Also #184.
