### ISSUE TITLE
Warrant canary not updated since 2018-04-2

### ISSUE THREAD

**Issue by strypey** [SilenceIM/Silence#747]
I notice that no code has been added to this repo since March, 2018. I also notice that the [warrant canary](https://silence.im/canary.txt) on your homepage at silence.im hasn't been updated since 2018-04-2. Is Silence still in active development? Has the project moved to a new source code repo? Or is it a dead parrot?

**Comment by BLeQuerrec** [comment]
I forgot to update the year... Pushing the fix.

**Comment by strypey** [comment]
> I forgot to update the year... Pushing the fix.

That's great! I just checked it and I can confirm the the year on the
warrant canary is now 2019. So we can now be confident that Silence has
not been compromised by law enforcement.

I'm still concerned that it could be compromised by changes in
dependencies or unpatched bugs. Is it still in active development? Will
there be new releases?

**Comment by zetaomegagon** [comment]
I'd also like to know if this project is still actively maintained. Thanks.

**Comment by ArchangeGabriel** [comment]
The project is still maintained. The developer has been quite busy (and will still be for a while), but some progresses have been made and should be released in the coming weeks or so.

**Comment by zetaomegagon** [comment]
Cool. Good to know!

**Comment by strypey** [comment]
> some progresses have been made and should be released in the coming weeks or so.

Is it possible to have a look at the code changes due to be released? Are they being worked on in a fork or something?

**Comment by strypey** [comment]
The warrant canary has been updated, so this issue can be closed. Further discussion of the maintenance status of Silence is happening in #703 .
