### ISSUE TITLE
New Maintainer + Revitalization Effort

### ISSUE THREAD

**Issue by PeekFreansCDN** [SilenceIM/Silence#754]
This app is slowly tumbling into the realm of the unkept and out of date. Those of us who are motivated and available to contribute long term to the continued viability of Silence as a solution for SMS/MMS encryption need to organize ourselves as a team.

I'm not going to pretend I'm solely capable of charting a road map to accomplish this though I will gladly donate my time to this. It seems maintaining seems to be an issue and issues aren't really being dealt so getting in contact with the current maintainer(s) and hacking away at bugs, feature requests and the overall integrity of Silence is imperative.

Who else here cares to make a concerted effort to turn this ship around?

**Comment by thiswillbeyourgithub** [comment]
I am not able to contribute in code but I think I would not be alone to be willing to contribute a few bucks a months to help any active developpement.

**Comment by MarionMoseby** [comment]
I could buy a premium play store version or contribute some non coding, i.e. translating, time

**Comment by sshelton76** [comment]
This is a good idea.  I just found out about this app after looking for a "googless" version of signal and was going to build something similar myself if I couldn't find it.

I am a dev.  I'll look into this and see what I can do to help.  I'd be maintaining my own fork anyways.
I'll see if my company would be interested in pitching in too.

**Comment by BLeQuerrec** [comment]
See https://github.com/SilenceIM/Silence/issues/753#issuecomment-516117577.

**Comment by strypey** [comment]
Great to see there are people keen to help the lead developer with work on Silence. Having more coders involved could help the project in a range of ways. If there is any need for help with integrating new volunteers into the development workflow, I'm happy to help with that if I can.
